const ILLER_XY = {
"Adana":[35.33,37.0],"Adıyaman":[38.28,37.76],"Afyonkarahisar":[30.54,38.76],"Ağrı":[43.05,39.72],"Amasya":[35.83,40.65],"Ankara":[32.86,39.93],"Antalya":[30.71,36.9],"Artvin":[41.82,41.18],"Aydın":[27.84,37.85],"Balıkesir":[27.89,39.65],"Bilecik":[29.98,40.15],"Bingöl":[40.5,38.88],"Bitlis":[42.11,38.4],"Bolu":[31.61,40.73],"Burdur":[30.29,37.72],"Bursa":[29.06,40.19],"Çanakkale":[26.41,40.15],"Çankırı":[33.62,40.6],"Çorum":[34.95,40.55],"Denizli":[29.09,37.78],"Diyarbakır":[40.22,37.91],"Edirne":[26.56,41.68],"Elazığ":[39.22,38.68],"Erzincan":[39.49,39.75],"Erzurum":[41.27,39.9],"Eskişehir":[30.52,39.77],"Gaziantep":[37.38,37.06],"Giresun":[38.39,40.91],"Gümüşhane":[39.48,40.46],"Hakkâri":[43.74,37.58],"Hatay":[36.16,36.2],"Isparta":[30.55,37.76],"Mersin":[34.64,36.81],"İstanbul":[28.98,41.01],"İzmir":[27.14,38.42],"Kars":[43.09,40.6],"Kastamonu":[33.78,41.38],"Kayseri":[35.49,38.72],"Kırklareli":[27.22,41.73],"Kırşehir":[34.16,39.15],"Kocaeli":[29.92,40.77],"Konya":[32.48,37.87],"Kütahya":[29.98,39.42],"Malatya":[38.31,38.35],"Manisa":[27.43,38.61],"Kahramanmaraş":[36.93,37.58],"Mardin":[40.74,37.31],"Muğla":[28.36,37.22],"Muş":[41.49,38.74],"Nevşehir":[34.71,38.62],"Niğde":[34.68,37.97],"Ordu":[37.88,40.98],"Rize":[40.52,41.02],"Sakarya":[30.4,40.78],"Samsun":[36.33,41.29],"Siirt":[41.94,37.93],"Sinop":[35.15,42.03],"Sivas":[37.02,39.75],"Tekirdağ":[27.51,40.98],"Tokat":[36.55,40.32],"Trabzon":[39.72,41.0],"Tunceli":[39.55,39.11],"Şanlıurfa":[38.79,37.16],"Uşak":[29.41,38.68],"Van":[43.38,38.49],"Yozgat":[34.81,39.82],"Zonguldak":[31.79,41.46],"Aksaray":[34.03,38.37],"Bayburt":[40.23,40.26],"Karaman":[33.22,37.18],"Kırıkkale":[33.51,39.85],"Batman":[41.13,37.88],"Şırnak":[42.46,37.52],"Bartın":[32.34,41.64],"Ardahan":[42.7,41.11],"Iğdır":[44.04,39.92],"Yalova":[29.27,40.65],"Karabük":[32.63,41.2],"Kilis":[37.12,36.72],"Osmaniye":[36.25,37.07],"Düzce":[31.16,40.84]
};
const ILLER = Object.keys(ILLER_XY);
for (const k in ILLER_XY) if (!CITY[k]) CITY[k] = ILLER_XY[k];
const BOLGE_ILLER = {
"Marmara":["Balıkesir","Bilecik","Bursa","Çanakkale","Edirne","İstanbul","Kırklareli","Kocaeli","Sakarya","Tekirdağ","Yalova"],
"Ege":["Afyonkarahisar","Aydın","Denizli","İzmir","Kütahya","Manisa","Muğla","Uşak"],
"Akdeniz":["Adana","Antalya","Burdur","Hatay","Isparta","Kahramanmaraş","Mersin","Osmaniye"],
"Karadeniz":["Amasya","Artvin","Bartın","Bayburt","Bolu","Çorum","Düzce","Giresun","Gümüşhane","Karabük","Kastamonu","Ordu","Rize","Samsun","Sinop","Tokat","Trabzon","Zonguldak"],
"İç Anadolu":["Aksaray","Ankara","Çankırı","Eskişehir","Karaman","Kayseri","Kırıkkale","Kırşehir","Konya","Nevşehir","Niğde","Sivas","Yozgat"],
"Doğu Anadolu":["Ağrı","Ardahan","Bingöl","Bitlis","Elazığ","Erzincan","Erzurum","Hakkâri","Iğdır","Kars","Malatya","Muş","Tunceli","Van"],
"Güneydoğu Anadolu":["Adıyaman","Batman","Diyarbakır","Gaziantep","Kilis","Mardin","Siirt","Şanlıurfa","Şırnak"]
};

const REGIONS = [
["Marmara Bölgesi","Marmara","#3D6EA5"],
["Ege Bölgesi","Ege","#2F8F76"],
["Akdeniz Bölgesi","Akdeniz","#1E9DB0"],
["Karadeniz Bölgesi","Karadeniz","#4C7A3E"],
["İç Anadolu Bölgesi","İç Anadolu","#C08A2E"],
["Doğu Anadolu Bölgesi","Doğu Anadolu","#8A4FB0"],
["Güneydoğu Anadolu Bölgesi","Güneydoğu Anadolu","#C1602E"]
];

const GENERAL = {
kirik:["Kırık (blok) dağlar, yer kabuğunun yan basınçla sertleşmiş tabakalarının faylar boyunca kırılmasıyla oluşur; yükselen bloklara horst, çöken bloklara graben denir.","Ege Bölgesi'nde Bakırçay, Gediz, Küçük Menderes ve Büyük Menderes çöküntü alanları; bu alanlar arasındaki Kaz, Madra, Yunt, Bozdağlar ve Aydın dağları tipik örneklerdir.","Ege'deki horst ve grabenler genellikle doğu–batı doğrultusunda uzanır; dağlar kıyıya dik uzandığı için kıyı ile iç kesim arasında ulaşım koridorları oluşur.","Kırık dağlar çoğunlukla eski masif kütlelerin yeniden kırılmasıyla oluşmuştur; fay hatları boyunca yükselme ve çökme birlikte görülür."],
kivrim:["Kıvrım dağları, Alp–Himalaya kuşağında Tersiyer'de (Alpin orojenez) oluşan genç dağlardır; Türkiye'deki dağların büyük bölümü bu gruptadır.","Ana kuşaklar: Kuzey Anadolu Dağları (Karadeniz'e paralel) ve Toroslar (Akdeniz'e paralel). Doğu Anadolu'nun büyük bölümü de kıvrımlıdır.","Genç oldukları için yüksek ve engebelidir; kıyıya paralel uzandıkları için iklim ve ulaşım üzerinde etkilidir (Kuzey Anadolu ve Toroslar iç kesimi kıyı iklimlerinden ayırır).","Toroslar üç bölümde incelenir: Batı Toroslar, Orta Toroslar, Güneydoğu Toroslar.","Türkiye'nin volkanik olmayan en yüksek zirvesi Cilo Dağları'ndaki Uludoruk Tepesi'dir (4135 m)."],
volkanik:["Volkanik dağlar Doğu ve İç Anadolu'da yoğundur ve neredeyse tamamı sönmüş volkandır.","Yükselti sıralaması: Ağrı (5137 m), Süphan (4058 m), Erciyes (3917 m).","Volkanik tüfler Kapadokya'nın peribacalarını oluşturmuştur (Erciyes, Hasan Dağı ve çevre volkanlar).","Göl türleri: Van Gölü volkanik set gölü, Nemrut kraterindeki göl krater gölü, Meke Gölü (Konya) ve Acıgöl (Nevşehir) maar gölüdür."],
fay:["Başlıca aktif fay sistemleri: Kuzey Anadolu Fay Hattı (KAF), Doğu Anadolu Fay Hattı (DAF) ve Ege'deki graben fayları.","KAF ve DAF Karlıova'da birleşir (Karlıova Üçlü Eklemi).","KAF ve DAF doğrultu atımlı faylardır. Ege'deki faylar çekme (normal fay) kökenlidir ve horst–graben yapısını oluşturur.","KAF Avrasya ile Anadolu levhalarının, DAF Anadolu ile Arap levhalarının sınırıdır."],
ova:["Türkiye'nin en büyük ovası Konya Ovası, en büyük delta ovası Çukurova'dır.","Oluşum türleri: delta ovaları (Çukurova, Bafra, Çarşamba), graben/çöküntü ovaları (Ege ovaları, Amik, Muş, Erzincan), kıyı ovaları (Antalya) ve kapalı havza tabanı ovaları (Konya).","Alüvyonlu topraklar tarıma çok elverişlidir; ancak Bursa, Adapazarı ve Çukurova gibi ovalarda sanayi ve yerleşim tarım arazilerini daraltmaktadır."],
plato:["Platolar İç Anadolu'da en yaygındır; genellikle kuru tarım (tahıl) ve koyunculuk yapılır.","Doğu Anadolu'daki yüksek platolarda (Kars, Ardahan, Erzurum çevresi) sert kışlar nedeniyle hayvancılık ön plandadır.","Toroslar'daki kalkerli platolarda karstik şekiller (dolin, uvala, polye, obruk) yaygındır."],
masif:["Masifler, çok eski jeolojik zamanlarda oluşmuş, uzun süre aşınmış sert ve kristalin kayaçlardan (granit, gnays, mikaşist) oluşan kütlelerdir.","Sert oldukları için sonraki hareketlerde kıvrılmak yerine kırılırlar; bu yüzden kırık dağlara (horst) dönüşebilirler.","Başlıca masifler: Menderes, Kırşehir, Kazdağ, Uludağ, Istranca, Niğde, Bitlis."],
levha:["Türkiye; Avrasya, Afrika ve Arap levhalarının etkileşim alanındadır. Anadolu ve Ege küçük levhalardır.","Arap Levhası'nın kuzeye hareketi Anadolu Levhası'nı sıkıştırır; Anadolu Levhası batıya kaçar ve saat yönünün tersine döner.","Levha sınırları deprem ve volkanizmanın yoğun olduğu kuşaklardır."],
goller:["Göl oluşum türleri KPSS'de sık sorulur: tektonik (çöküntü) göller, karstik göller, volkanik göller (krater/maar ve set gölleri), buzul (sirk) gölleri, kıyı set (lagün) gölleri ve doğal/yapay set (heyelan, alüvyon, baraj) gölleri.","Türkiye'nin en büyük gölü Van Gölü'dür (volkanik set gölü, sodalı/acı sulu); ikinci büyük göl Tuz Gölü'dür (tektonik, en tuzlu göl).","Karstik göllere örnek: Beyşehir ve Eğirdir (Göller Yöresi); volkanik krater/maar göllerine örnek: Nemrut Krater Gölü, Acıgöl (Nevşehir), Meke Gölü.","Kıyı set (lagün) göllerine örnek: Terkos ve Küçükçekmece (İstanbul); heyelan set gölüne örnek: Tortum Gölü (Erzurum)."],
nehirler:["Türkiye akarsuları; Karadeniz, Marmara, Ege, Akdeniz, Basra Körfezi ve Hazar Denizi havzalarına dökülür.","Kızılırmak Türkiye sınırları içindeki en uzun nehirdir; Yeşilırmak ve Sakarya Karadeniz'e, Meriç Ege Denizi'ne ulaşır.","Fırat ve Dicle Basra Körfezi'ne; Aras ve Çoruh Hazar havzasına yönelir. Seyhan, Ceyhan ve Asi Akdeniz'e dökülür."],
akarsular:["Büyük Menderes, Küçük Menderes ve Gediz Ege kıyılarındaki graben ovalarını geçerek Ege Denizi'ne ulaşır.","Murat, Fırat'ın önemli kollarındandır; Porsuk ve Delice ise Sakarya ve Kızılırmak sistemlerinin kollarıdır.","Akarsu güzergâhları harita ölçeğinde yaklaşık gösterilmiştir; hidrografik sınırlar ve kollar için kaynak PDF esas alınmıştır."],
bolge:["Türkiye, 1941'de toplanan I. Coğrafya Kongresi'nde iklim, bitki örtüsü, tarım ürünleri, yeryüzü şekilleri ve ulaşım gibi ölçütler kullanılarak 7 coğrafi bölgeye ayrılmıştır: Marmara, Ege, Akdeniz, Karadeniz, İç Anadolu, Doğu Anadolu, Güneydoğu Anadolu.","KPSS'de sık karıştırılan konu: bu 7 bölge \"coğrafi bölge\"dir; ayrıca AB'ye uyum için oluşturulan İBBS (İstatistiki Bölge Birimleri Sınıflandırması) vardır: Düzey 1'de 12 bölge, Düzey 2'de 26 alt bölge, Düzey 3'te 81 il yer alır.","Yüzölçümü büyüklük sırası (büyükten küçüğe): Doğu Anadolu, İç Anadolu, Akdeniz, Ege, Karadeniz, Marmara, Güneydoğu Anadolu.","Nüfus yoğunluğu en fazla bölge Marmara'dır (sanayi ve hizmet sektörü yoğun); nüfus yoğunluğu en az bölge Doğu Anadolu'dur."],
komsu:["Türkiye'nin kara sınırı bulunan 8 komşusu vardır: Yunanistan, Bulgaristan, Gürcistan, Ermenistan, Azerbaycan (Nahçıvan dahil), İran, Irak ve Suriye.","Batıda Yunanistan ve Bulgaristan; doğuda Gürcistan, Ermenistan, Azerbaycan ve İran; güneyde Irak ve Suriye bulunur.","Kara sınırlarının uzunlukları kıyı ve sınır düzenlemelerine göre kaynaklarda farklı yuvarlanabilir; bu harita ülke adlarını ve gerçek Natural Earth sınır geometrilerini gösterir, kesin kilometre sıralaması iddiası taşımaz."],
iller:["Türkiye'de 81 il vardır. Bölgelere göre dağılım: Karadeniz 18, İç Anadolu 13, Doğu Anadolu 14, Marmara 11, Güneydoğu Anadolu 9, Ege 8, Akdeniz 8.","En çok ile sahip bölge Karadeniz'dir; en az ile sahip bölgeler Ege ve Akdeniz'dir (8'er il).","İstanbul ve Çanakkale iki kıtada toprağı olan illerdir (Avrupa ve Asya)."]
};

const NOTES = {
"Kaz Dağları":["Balıkesir ve Çanakkale arasında, Edremit Körfezi'nin kuzeyindedir; antik çağda İda Dağı olarak anılırdı.","Kazdağ Masifi'nin kırılmasıyla oluşan kırık (horst) dağdır; en yüksek noktası Karataş Tepesi'dir (yaklaşık 1774 m).","Kaz Dağları Milli Parkı ve endemik Kazdağı göknarıyla bilinir."],
"Madra Dağı":["Ege'nin kuzeyinde yer alan Ege kırık dağlarından biridir.","Sınavlarda Kaz, Madra, Yunt, Bozdağlar, Aydın ve Menteşe dağları birlikte Ege'nin kırık dağları olarak sorulur."],
"Yunt Dağı":["Manisa yöresinde yer alan, Ege kırık (horst) dağlarından biridir.","Ege kırık dağları grubuyla birlikte hatırlayın: Kaz, Madra, Yunt, Bozdağlar, Aydın, Menteşe."],
"Bozdağlar":["Gediz ve Küçük Menderes grabenleri arasında uzanan kırık (horst) dağdır.","En yüksek noktası Bozdağ'dır (yaklaşık 2159 m); Menderes Masifi'nin bir parçasıdır."],
"Aydın Dağları":["Küçük Menderes ve Büyük Menderes grabenleri arasındaki horst'tur.","Menderes Masifi'nin bir parçası olduğu için hem masif hem kırık dağ örneği olarak sorulur."],
"Menteşe Dağları":["Muğla çevresinde, Ege Bölgesi'nin güney kesiminde yer alan kırık (horst) dağdır; adını Muğla'nın Menteşe ilçesinden alır.","Ege kırık dağları arasında sayılır: Kaz, Madra, Yunt, Bozdağlar, Aydın, Menteşe."],
"Nur (Amanos) Dağları":["Hatay ve Osmaniye çevresinde, Akdeniz kıyısına paralel uzanır; kırık dağ olarak sınıflandırılır.","Belen Geçidi bu dağlardan geçer ve Akdeniz'i Suriye'ye bağlayan önemli bir geçittir.","Amik Ovası ile Akdeniz arasında yer alır."],
"Bakırçay Grabeni":["Bakırçay Ovası'nın içinde uzanan Ege çöküntü alanıdır.","Kaynakta Kaz, Madra ve Yunt horstlarıyla birlikte Ege'nin kırık dağ-graben sisteminin bir parçası olarak gösterilir."],
"Gediz Grabeni":["Manisa ve Alaşehir çevresinde doğu-batı doğrultusunda uzanan çöküntü alanıdır.","Gediz Ovası bu grabenin tabanında yer alır; Bozdağlar ve Yunt Dağı çevredeki horst örnekleridir."],
"Küçük Menderes Grabeni":["Ödemiş, Tire ve Selçuk çevresinde uzanan Ege çöküntü alanıdır.","Bozdağlar ile Aydın Dağları arasındaki graben sisteminin parçasıdır."],
"Büyük Menderes Grabeni":["Denizli, Nazilli, Aydın ve Söke boyunca uzanan geniş çöküntü alanıdır.","Büyük Menderes Ovası graben tabanında gelişmiştir; Aydın Dağları çevredeki horst örneklerindendir."],
"Samanlı Dağları":["Marmara Bölgesi'nde, İznik Gölü ile Marmara kıyısı arasında (Yalova, Kocaeli, Bursa çevresi) uzanan kıvrım dağıdır.","Marmara'daki dağlar sorulurken Uludağ ve Istranca masif, Samanlı ise kıvrım dağı olarak ayrılır."],
"Beydağları":["Antalya'nın batısında Batı Toroslar'ın bir parçasıdır (Teke Yöresi).","Batı Toroslar: Beydağları, Akdağ, Katrancık gibi dağlardan oluşur."],
"Geyik Dağları":["Orta Toroslar içinde, Antalya, Konya ve Karaman yöresinde yer alır.","Orta Toroslar'ın ana dağları: Geyik Dağları, Bolkar Dağları, Aladağlar."],
"Bolkar Dağları":["Orta Toroslar'da, Niğde, Mersin ve Karaman çevresindedir; en yüksek noktası Medetsiz Tepesi'dir (yaklaşık 3524 m).","Bolkar Dağları ile Aladağlar arasında Ecemiş Fayı ve koridoru bulunur."],
"Aladağlar":["Niğde, Adana ve Kayseri arasında Orta Toroslar'dadır; en yüksek zirvesi Demirkazık Tepesi'dir (3756 m).","Aladağlar Milli Parkı; dağcılık ve doğa sporlarıyla bilinir."],
"Munzur Dağları":["Tunceli ve Erzincan arasında, Doğu Anadolu Bölgesi'nde yer alır.","Munzur Suyu bu dağlardan doğar ve Fırat'a karışır; Munzur Vadisi Milli Parkı buradadır."],
"Mercan Dağları":["Erzincan çevresinde, Doğu Anadolu'daki kıvrım dağlarındandır.","Doğu Anadolu'nun kıvrım dağları (Munzur, Mercan, Palandöken, Allahuekber) birlikte sorulur."],
"Cudi Dağı":["Şırnak'ta, Güneydoğu Toroslar üzerinde yer alır.","Nuh'un Gemisi rivayetlerinde Cudi Dağı'na atıf yapılır (Ağrı Dağı ile karıştırılmamalı)."],
"Hakkâri Dağları":["Cilo ve Sat Dağları bu kuşaktadır; Cilo'daki Uludoruk Tepesi (4135 m) Türkiye'nin volkanik olmayan en yüksek zirvesidir.","Güneydoğu Toroslar'ın doğu ucudur; Türkiye'de buzulların görüldüğü dağlar arasındadır."],
"Köroğlu Dağları":["Bolu, Ankara ve Çankırı arasında, Batı Karadeniz'de Kuzey Anadolu Dağları'nın bir parçasıdır.","Bolu Dağı geçidi (TEM otoyolu ve Bolu Dağı Tüneli) bu kuşaktadır."],
"Ilgaz Dağları":["Kastamonu ve Çankırı arasındadır; Ilgaz Dağı Milli Parkı ve kayak merkeziyle bilinir.","En yüksek noktası Büyük Hacet Tepesi'dir (yaklaşık 2587 m)."],
"Küre Dağları":["Kastamonu ve Bartın çevresinde, Batı Karadeniz'de Karadeniz kıyısına paralel uzanır.","Küre Dağları Milli Parkı ve Küre'deki bakır yatakları ile bilinir."],
"Canik Dağları":["Samsun ve Ordu arasında, Orta Karadeniz'de Kuzey Anadolu Dağları'nın parçasıdır.","Karadeniz'e paralel uzanan bu dağlar, iç kesime nem girişini sınırlar."],
"Kaçkar Dağları":["Rize, Artvin ve Erzurum arasında yer alır; en yüksek noktası Kaçkar Dağı'dır (3937 m), Kuzey Anadolu Dağları'nın en yükseğidir.","Yaylalar ve buzul gölleri ile bilinir; Rize Türkiye'nin en fazla yağış alan ilidir."],
"Yalnızçam Dağları":["Ardahan ve Artvin arasında, Doğu Karadeniz Dağları'nın kuzeydoğu uzantısıdır.","Yalnızçam Dağları'nda kayak turizmi (Ardahan) ve sert kışlar dikkat çeker."],
"Allahuekber Dağları":["Erzurum ve Kars arasında, Sarıkamış yöresindedir.","1914–1915 Sarıkamış Harekâtı ve Sarıkamış kayak merkezi ile bilinir."],
"Palandöken Dağları":["Erzurum'un güneyinde yer alır; kış sporları ve kayak merkeziyle bilinir.","Türkiye'nin başlıca kayak merkezleri: Palandöken (Erzurum), Erciyes (Kayseri), Uludağ (Bursa), Kartalkaya (Bolu), Sarıkamış (Kars)."],
"Ağrı Dağı":["5137 m ile Türkiye'nin en yüksek dağıdır; Ağrı ve Iğdır arasında yer alan sönmüş bir volkandır.","Sürekli karlı ve buzulludur; yanındaki Küçük Ağrı 3896 m'dir.","Nuh'un Gemisi rivayetleriyle anılır."],
"Tendürek Dağı":["Ağrı ve Doğubayazıt çevresinde, Doğu Anadolu'da yer alır; yaklaşık 3533 m.","Türkiye'de tamamen sönmemiş, fümerol etkinliği gösteren volkanlardan biridir."],
"Süphan Dağı":["Bitlis'in Adilcevaz ilçesi yakınında, Van Gölü'nün kuzeyindedir (4058 m).","Türkiye'nin Ağrı'dan sonra en yüksek ikinci volkanik dağıdır."],
"Nemrut Dağı":["Bitlis'in Tatvan ilçesinde, Van Gölü'nün batı ucundadır; krater gölüyle bilinir.","Volkanik püskürmelerin Murat Nehri'nin kolunu tıkamasıyla Van Gölü oluşmuştur (volkanik set gölü).","Adıyaman'daki Nemrut Dağı (heykelleri ve kral mezarı) farklı bir dağdır; ikisi karıştırılmamalı."],
"Bingöl Dağı":["Bingöl çevresinde, Doğu Anadolu'da yer alan volkanik dağdır (yaklaşık 3258 m).","Doğu Anadolu'daki volkanik dağlar: Ağrı, Tendürek, Süphan, Nemrut, Bingöl."],
"Karacadağ":["Diyarbakır ve Şanlıurfa arasında, Güneydoğu Anadolu'daki geniş lav (bazalt) platosudur.","Karacadağ pirinci (Diyarbakır) coğrafi işaretli ürünler arasında sayılır."],
"Erciyes Dağı":["Kayseri'de yer alır; 3917 m ile İç Anadolu'nun en yüksek dağıdır (sönmüş volkan).","Kış turizmi ve Kapadokya'daki tüf oluşumuyla ilişkilendirilir."],
"Hasan Dağı":["Aksaray'da, Tuz Gölü'nün güneydoğusunda yer alır; yaklaşık 3253 m, çift tepelidir.","Kapadokya'nın tüf ve peribacası oluşumuna katkıda bulunan volkanlardandır."],
"Melendiz Dağı":["Aksaray ve Niğde arasında yer alan volkanik dağdır.","Melendiz Çayı, Ihlara Vadisi'ni açmıştır."],
"Karadağ (Karaman)":["Karaman'da, Konya Ovası'nın güneyinde yer alan volkanik koni dağıdır.","Binbir Kilise kalıntıları Karadağ eteklerindedir."],
"Kula Volkanları":["Manisa'nın Kula ilçesinde yer alır; Türkiye'nin en genç volkanik alanlarından biridir.","Kula–Salihli Jeoparkı, UNESCO Küresel Jeoparklar Ağı üyesidir."],

"Kuzey Anadolu Fay Hattı":["Karlıova'dan Saros Körfezi'ne yaklaşık 1500 km uzanır; sağ yanal doğrultu atımlı fay hattıdır.","Avrasya ve Anadolu levhalarının sınırıdır.","Bilinen depremler: 1939 Erzincan (7.9), 1999 İzmit/Marmara (7.4) ve Düzce (7.2).","Türkiye'nin en aktif ve en çok bilinen fay hattıdır."],
"Doğu Anadolu Fay Hattı":["Karlıova'dan Hatay'a (İskenderun Körfezi) uzanır; sol yanal doğrultu atımlıdır.","Anadolu ve Arap levhalarının sınırıdır.","Bilinen depremler: 2020 Elazığ Sivrice (6.8) ve 6 Şubat 2023 Kahramanmaraş depremleri (Pazarcık merkezli 7.7, Elbistan merkezli 7.6; AFAD)."],
"Gediz Grabeni Fayı":["Alaşehir, Salihli ve Manisa boyunca uzanır; batıda İzmir Körfezi'ne ulaşan Gediz Nehri çevresindeki graben ovasını oluşturur.","Ege'de doğu–batı uzanan çekme (normal) faylardan biridir."],
"Büyük Menderes Grabeni Fayı":["Denizli, Nazilli, Aydın ve Söke çizgisi boyunca uzanır.","Büyük Menderes Nehri graben tabanından akar ve Ege Denizi'ne dökülür; Pamukkale travertenleri Denizli çevresindedir."],
"Küçük Menderes Grabeni Fayı":["Ödemiş, Tire ve Selçuk yöresinden geçer; Küçük Menderes Nehri graben tabanından akar.","Bozdağlar ile Aydın Dağları arasındaki graben bu hat üzerindedir."],
"Fethiye–Burdur Fay Zonu":["Batı Toroslar'da Fethiye'den Burdur'a uzanan KD–GB doğrultulu fay zonudur.","1971 Burdur depremi (6.2) ve 1957 Fethiye depremi bu bölgede yaşanmıştır."],
"Tuz Gölü Fayı":["Şereflikoçhisar ile Aksaray arasında Tuz Gölü çukurunu sınırlayan fay zonudur.","Tuz Gölü, tektonik çukurlukta oluşmuş bir göldür; Van Gölü'nden sonra Türkiye'nin ikinci büyük gölüdür ve tuz üretimi için önemlidir."],
"Ecemiş Fayı":["Orta Toroslar'da Pozantı, Çamardı ve Yahyalı çizgisinde uzanır.","Bolkar Dağları ile Aladağlar'ı ayıran Ecemiş Koridoru bu fay boyunca uzanır."],

"Çukurova":["Adana ve Mersin'de, Seyhan ve Ceyhan nehirlerinin oluşturduğu Türkiye'nin en büyük delta ovasıdır.","Pamuk, narenciye, mısır ve ikinci ürün soya gibi ürünlerle bilinir."],
"Amik Ovası":["Hatay'da graben (çöküntü) ovasıdır; Asi Nehri buradan geçer.","Eski Amik Gölü kurutularak tarım alanına dönüştürülmüştür; pamuk ve tahıl yetiştirilir."],
"Antalya Ovası":["Antalya'da kıyı ovasıdır; seracılık ve turizmle bilinir.","Türkiye'de seracılığın en yoğun olduğu yerlerden biridir."],
"Bafra Ovası":["Samsun'da Kızılırmak deltası üzerindedir; tütün ve çeltik yetiştirilir.","Kızılırmak Deltası'ndaki Balık Gölleri kuş türleri açısından önemlidir."],
"Çarşamba Ovası":["Samsun'da, Yeşilırmak deltasının oluşturduğu ovadır.","Bafra ile birlikte Karadeniz'in en geniş delta ovalarındandır."],
"Harran Ovası":["Şanlıurfa'da GAP kapsamında Atatürk Barajı'ndan sulanan ova; Şanlıurfa–Harran tüneli ile sulanır.","Pamuk üretimiyle öne çıkar; GAP sulama projesinin en belirgin kazanımlarından biridir."],
"Bursa Ovası":["Nilüfer Çayı'nın oluşturduğu, sanayi ve tarımın iç içe olduğu ova.","Sanayi ve yerleşimin tarım arazilerini daraltmasına sık verilen örnektir."],
"Ergene (Trakya) Ovası":["Ergene Nehri havzasındadır; Trakya'da ayçiçeği ve buğday üretiminin merkezidir.","Ergene Havzası sanayi kaynaklı kirlilik tartışmalarıyla anılır."],
"Adapazarı Ovası":["Sakarya Nehri'nin oluşturduğu alüvyon ovadır.","Kuzey Anadolu Fay Hattı üzerinde yer alır; 1999 depreminde zemin sıvılaşması nedeniyle büyük hasar görmüştür."],
"Erzurum Ovası":["Karasu (Fırat'ın kolu) çevresinde, Doğu Anadolu'nun yüksek ovalarından biridir.","İklimi sert karasaldır; tahıl ve hayvancılık ön plandadır."],
"Muş Ovası":["Murat Nehri çevresinde, Doğu Anadolu'nun en geniş ovalarındandır.","Buğday ve şeker pancarı yetiştirilir."],
"Iğdır Ovası":["Aras Nehri kıyısında; kışları Doğu Anadolu'ya göre ılıman, yazları sıcaktır.","Pamuk, kayısı ve çeltik yetiştirilebilen ender yerlerdendir; Doğu Anadolu'nun Çukurova'sı olarak anılır."],
"Malatya Ovası":["Fırat havzasında; kayısı üretimi ile bilinir.","Malatya kayısısı Türkiye'nin kayısı üretiminin büyük bölümünü karşılar."],
"Erzincan Ovası":["Karasu (Fırat'ın kolu) çevresinde, Kuzey Anadolu Fay Hattı üzerindedir.","1939 Erzincan depremi (7.9) ve 1992 Erzincan depremi bu ovada yaşanmıştır."],
"Bakırçay Ovası":["Bergama çevresinde, Bakırçay'ın oluşturduğu ovadır.","Ege'de pamuk ve tahıl tarımı yapılır."],
"Gediz Ovası":["Manisa'da, Gediz Grabeni'nin taban ovasıdır.","Manisa kuru üzüm üretiminin merkezidir; pamuk ve sebze de yetiştirilir."],
"Küçük Menderes Ovası":["Ödemiş, Tire ve Selçuk çevresinde, Küçük Menderes Grabeni'nin taban ovasıdır.","Ödemiş patatesi ile bilinir."],
"Büyük Menderes Ovası":["Aydın'da Büyük Menderes Grabeni'nin taban ovasıdır; Ege'nin en verimli ovalarından biridir.","Aydın incirinin ana üretim alanıdır; pamuk da yetiştirilir."],
"Konya Ovası":["Türkiye'nin en büyük ovasıdır; kapalı havza tabanıdır.","Buğday, şeker pancarı ve yem bitkisi üretimi yüksektir; Konya Ovası Projesi (KOP) sulamayı genişletir.","Yeraltı suyu çekilmesi obruk (çöküntü çukuru) oluşumunu artırmıştır."],

"Haymana Platosu":["Ankara'nın güneyinde, İç Anadolu'da kuru tarım (tahıl) ve koyunculuk alanıdır.","Haymana çevresi termal kaynaklarıyla da bilinir."],
"Cihanbeyli Platosu":["Konya'nın kuzeyinde, Tuz Gölü'nün batısında yer alır.","Bozkır iklimi görülür; tahıl ve koyunculuk yapılır."],
"Obruk Platosu":["Konya, Karaman ve Aksaray çevresinde yer alır; kalkerli yapıdadır.","Karstik çöküntü çukurları olan obruklar ve Obruk (Karapınar) çevresindeki göller bu platoda görülür."],
"Uzunyayla Platosu":["Kayseri ve Sivas çevresinde yer alır.","Yaylacılık ve hayvancılık için elverişlidir."],
"Bozok Platosu":["Yozgat ve Çorum çevresinde yer alır.","Kurak ve soğuk kışlı iklim; tahıl tarımı ve hayvancılık."],
"Eskişehir Platosu":["İç Anadolu'nun batı kesiminde, Porsuk Çayı çevresindedir.","Lületaşı yatakları ile bilinir."],
"Teke Platosu":["Akdeniz Bölgesi'nde Antalya Körfezi'nin batısındaki Teke Yöresi'nde yer alır.","Kalkerli olduğu için karstik şekiller yaygındır."],
"Kars Platosu":["Kars ve Ardahan'da lav platosudur; Türkiye'nin en soğuk yerleri arasındadır.","Hayvancılık, Kars kaşarı ve bal üretimi öne çıkar."],
"Gaziantep Platosu":["Gaziantep'te kalkerli plato; antepfıstığı, zeytin ve bağcılıkla bilinir.","Antepfıstığı üretiminde Gaziantep, Şanlıurfa ve Siirt öne çıkar."],
"Mardin Eşiği (Platosu)":["Mardin çevresinde, Mezopotamya ovasına açılan eşiktir.","Buğday ve mercimek yetiştirilir."],
"Ceylanpınar Platosu":["Şanlıurfa'da, Suriye sınırı boyunca uzanır.","Ceylanpınar Tarım İşletmesi (TİGEM) büyük ölçekli tarımsal üretimiyle bilinir."],

"Menderes Masifi":["Ege Bölgesi'nde, Türkiye'nin en geniş kristalin masiflerinden biridir.","Bozdağlar ve Aydın Dağları bu masifin kırılmasıyla oluşan horst'lardır."],
"Kazdağ Masifi":["Balıkesir ve Çanakkale arasında, Ege kıyısına yakın kristalin bir kütledir.","Kaz Dağları bu masifin en belirgin yükselti bölümüdür."],
"Uludağ Masifi":["Bursa'da yer alır; 2543 m ile Marmara'nın en yüksek dağıdır.","Granit yapılıdır; kış turizmi (Uludağ Milli Parkı) ile bilinir."],
"Istranca (Yıldız) Masifi":["Trakya'nın kuzeyinde, Karadeniz kıyısına yakın uzanan alçak ve yaşlı masiftir.","Türkiye'nin Avrupa kıtasındaki tek masifidir; en yüksek noktası Mahya Dağı'dır (yaklaşık 1031 m)."],
"Zonguldak Masifi":["Batı Karadeniz'de, Zonguldak çevresinde yer alan yaşlı kristalin kütledir.","Türkiye'nin masif arazileri arasında gösterilir; çevresindeki taş kömürü sahalarıyla birlikte değerlendirilir."],
"Kırşehir Masifi":["İç Anadolu'da Kırşehir çevresinde, Kızılırmak kavsinin içinde yer alan kristalin kütledir.","İç Anadolu'daki en önemli masiftir."],
"Sultan Dağları Masifi":["İç Anadolu ile Akdeniz geçişinde, Afyonkarahisar-Konya-Isparta çevresinde uzanan yaşlı kütledir.","Kaynak haritalarda Türkiye'nin masif arazileri arasında gösterilir; çevresindeki faylanma ve yükseltilerle birlikte değerlendirilir."],
"Niğde Masifi":["Niğde çevresinde, Toroslar ile İç Anadolu arasındaki kristalin kütledir.","Sık sorulan karşılaştırma: Kırşehir ve Niğde masifleri İç Anadolu'daki masiflerdir."],
"Alanya-Anamur Masifi":["Akdeniz Bölgesi'nde Alanya-Anamur kıyı kuşağında yer alan yaşlı kristalin kütledir.","Toros kuşağındaki masif alanlardan biri olarak kaynak haritalarda gösterilir."],
"Malatya-Pötürge Masifi":["Doğu Anadolu'da Malatya ve Pötürge çevresinde yer alan yaşlı kristalin kütledir.","Doğu Anadolu masifleri arasında Bitlis Masifi ile birlikte değerlendirilir."],
"Mardin-Derik Masifi":["Güneydoğu Anadolu'da Mardin-Derik çevresinde yer alan yaşlı kütledir.","Kaynak haritalarda Güneydoğu Anadolu'nun masif alanları arasında gösterilir."],
"Bitlis Masifi":["Bitlis ve Muş çevresinde, Van Gölü'nün güneyinde yer alır.","Güneydoğu Toroslar'ın doğu uzantısı olarak da incelenir."],

"Yunanistan":["Türkiye'nin batısında, Ege ve Trakya üzerinden kara komşusudur.","Edirne ve Meriç Nehri çevresindeki kara sınırı Türkiye'nin batı komşuluk kuşağındadır."],
"Bulgaristan":["Türkiye'nin kuzeybatısında, Trakya üzerinden kara komşusudur.","Kırklareli ve Edirne çevresi Bulgaristan sınır kuşağında yer alır."],
"Gürcistan":["Türkiye'nin kuzeydoğusunda, Artvin ve Ardahan çevresinden kara komşusudur.","Doğu Karadeniz'in doğu kesiminde yer alır."],
"Ermenistan":["Türkiye'nin doğusunda, Kars ve Iğdır çevresinden kara komşusudur.","Sınır kuşağı Doğu Anadolu'nun kuzeydoğu kesimindedir."],
"Azerbaycan (Nahçıvan dahil)":["Türkiye'nin doğusunda Nahçıvan Özerk Cumhuriyeti üzerinden kısa bir kara sınırı vardır.","Bu nedenle Azerbaycan, ana karası Türkiye'ye bitişik olmasa da Türkiye'nin kara komşuları arasında sayılır."],
"İran":["Türkiye'nin doğusunda, Doğu Anadolu'nun doğu ve güneydoğu kuşağından kara komşusudur.","Van, Ağrı ve Hakkâri çevreleri İran sınır kuşağıyla ilişkilidir."],
"Irak":["Türkiye'nin güneydoğusunda, Hakkâri ve Şırnak çevresinden kara komşusudur.","Sınır kuşağı Güneydoğu Toroslar'ın doğu bölümüne yakın uzanır."],
"Suriye":["Türkiye'nin güneyinde, Akdeniz ve Güneydoğu Anadolu boyunca kara komşusudur.","Hatay, Kilis, Gaziantep, Şanlıurfa, Mardin ve Şırnak çevreleri Suriye sınır kuşağındadır."],

"Avrasya Levhası":["Türkiye'nin kuzeyinde; KAF ile Anadolu Levhası'ndan ayrılır.","Karadeniz'in altı Avrasya Levhası üzerindedir."],
"Anadolu Levhası":["Türkiye'nin büyük bölümünü kapsayan küçük levhadır.","Arap Levhası'nın kuzeye hareketiyle sıkışır, batıya kaçar ve saat yönünün tersine döner.","Sınırları: KAF (kuzey), DAF (doğu/güneydoğu)."],
"Arap Levhası":["Güneydoğuda yer alır; kuzeye hareket ederek Anadolu ve Avrasya levhalarına sıkışır.","DAF, Anadolu ile Arap levhası arasındaki sınırdır; Bitlis–Zagros kenet kuşağı ile ilişkilidir."],
"Afrika Levhası":["Türkiye'nin güneyinde, Akdeniz tabanında yer alır.","Girit–Kıbrıs yayları boyunca Anadolu ve Ege levhalarının altına dalar."],

"Marmara Bölgesi":["Yüzölçümü en küçük ikinci bölgedir fakat nüfusça en kalabalık ve nüfus yoğunluğu en fazla bölgedir.","Sanayi, ticaret ve hizmet sektörünün en gelişmiş olduğu bölgedir; tarım alanlarının payı diğer bölgelere göre azdır.","Karadeniz ile Ege/Akdeniz arasında geçiş konumundadır; İstanbul ve Çanakkale boğazlarıyla Asya ve Avrupa'yı birbirine bağlar."],
"Ege Bölgesi":["Kıyı çizgisi girinti çıkıntısı en fazla olan bölgedir (Ege tipi/enine kıyı); dağlar kıyıya dik uzanır.","Kırık (horst-graben) dağların tipik görüldüğü bölgedir; zeytin, tütün, incir, üzüm ve pamuk üretiminde önde gelir.","İzmir bölgenin nüfus ve sanayi bakımından en büyük ilidir."],
"Akdeniz Bölgesi":["Toroslar kıyıya paralel uzanır; kıyı ile iç kesim arasında iklim ve bitki örtüsü farkı belirgindir.","Turunçgil, muz ve seracılıkta (özellikle Antalya) Türkiye'nin önde gelen bölgesidir.","Çukurova, bölgenin ve Türkiye'nin en büyük delta ovasıdır."],
"Karadeniz Bölgesi":["Türkiye'nin en fazla yağış alan bölgesidir; her mevsim yağışlı ılıman iklim görülür.","En fazla ile sahip bölgedir (18 il); dağların kıyıya paralel uzanması iç kesimlerle ulaşımı zorlaştırır.","Çay (Rize/Doğu Karadeniz) ve fındık (Orta/Batı Karadeniz) üretiminde Türkiye'de birinci bölgedir."],
"İç Anadolu Bölgesi":["Yüzölçümü bakımından ikinci büyük bölgedir; karasal iklim ve step (bozkır) bitki örtüsü egemendir.","Tahıl (özellikle buğday) üretiminde Türkiye'nin ambarı kabul edilir; hayvancılıkta küçükbaş önemlidir.","Başkent Ankara bu bölgededir; kırık ve volkanik dağlar ile geniş ova/platolar bir arada görülür."],
"Doğu Anadolu Bölgesi":["Yüzölçümü en büyük bölgedir; ortalama yükseltisi de Türkiye'de en fazladır.","Kışları en sert ve en uzun süren bölgedir; nüfus yoğunluğu en düşük bölgelerdendir.","Büyükbaş hayvancılık (özellikle sığır) önemlidir; volkanik dağlar (Ağrı, Süphan, Nemrut) ve yüksek ovalar/platolar (Erzurum-Kars) tipiktir."],
"Güneydoğu Anadolu Bölgesi":["Yüzölçümü en küçük bölgedir; Suriye sınırı boyunca uzanır.","Karasal iklime yakın, sıcak ve kurak yazlar görülür; GAP (Güneydoğu Anadolu Projesi) barajlarıyla sulu tarım alanı genişlemiştir.","Antepfıstığı, pamuk ve zeytin üretiminde öne çıkar; Harran Ovası GAP'ın simge tarım alanlarındandır."],

"Van Gölü":["Türkiye'nin en büyük gölüdür (yaklaşık 3.700 km²); Nemrut ve Süphan volkanlarının Murat Nehri koluna set çekmesiyle oluşan bir volkanik set gölüdür.","Sodalı (alkali) ve acı sulu bir göldür; gölde yaşayabilen tek balık türü inci kefalidir.","Kışın Van Gölü çevresinde oluşan 'Van kedisi' ile karıştırılmamalıdır; coğrafi olarak göl kıyısındaki Edremit, Erciş, Tatvan, Ahlat, Adilcevaz ilçeleriyle anılır."],
"Tuz Gölü":["Türkiye'nin ikinci büyük gölüdür; tektonik kökenli sığ bir çöküntü gölüdür.","Türkiye'nin en tuzlu gölüdür; yazın büyük ölçüde kuruyarak tuz tabakası oluşturur, tuz üretimi (çömlekçi tuzu) yapılır.","Aksaray, Konya ve Ankara illeri arasında, İç Anadolu'nun ortasında yer alır."],
"Beyşehir Gölü":["Türkiye'nin üçüncü büyük gölü ve tatlı su göllerinin en büyüğüdür.","Karstik ve tektonik etkilerin bir arada görüldüğü, Göller Yöresi'nin (Isparta-Konya-Antalya) simge gölüdür.","Konya ve Isparta il sınırları içinde yer alır."],
"Eğirdir Gölü":["Göller Yöresi'nde, Isparta'da yer alan tatlı su gölüdür.","Karstik şekillerin ve tektonik çöküntünün birlikte etkili olduğu kabul edilir; alabalık üretimi ve turizmle bilinir."],
"İznik Gölü":["Bursa çevresinde, Samanlı Dağları'nın güneyinde yer alan tektonik kökenli bir göldür.","Kıyısındaki İznik ilçesi, tarihi çinileri ve Bizans/Osmanlı dönemi eserleriyle bilinir."],
"Sapanca Gölü":["Sakarya'da, Kuzey Anadolu Fay Hattı'na yakın tektonik kökenli bir göldür.","İstanbul-Ankara karayolu ve TEM güzergâhı üzerinde, içme suyu kaynağı olarak da önemlidir."],
"Manyas (Kuş) Gölü":["Balıkesir'de tektonik kökenli bir göldür; kıyısındaki Kuş Cenneti Milli Parkı kuş göç yollarında önemli bir sulak alandır."],
"Uluabat Gölü":["Bursa'da tektonik kökenli, sazlık ve kuş türleri bakımından zengin bir göldür; Ramsar Sözleşmesi kapsamında korunan sulak alanlardandır."],
"Salda Gölü":["Burdur'da, karstik ve tektonik etkilerin bir arada görüldüğü, beyaz kumsalları ve turkuaz rengiyle bilinen bir göldür.","Mineral yapısı nedeniyle NASA tarafından Mars'taki Jezero Krateri ile karşılaştırılmıştır."],
"Acıgöl (Denizli)":["Denizli'de tektonik kökenli, tuzlu ve sodalı bir göldür; Nevşehir'deki volkanik krater (maar) gölü olan Acıgöl ile karıştırılmamalıdır."],
"Burdur Gölü":["Burdur'da tektonik kökenli, tuzlu bir göldür; Fethiye-Burdur Fay Zonu'nun etkisiyle oluşan çöküntü alanındadır."],
"Akşehir Gölü":["Konya-Afyonkarahisar sınırında, tektonik kökenli sığ ve tuzlu bir göldür; komşusu Eber Gölü ile bir sistem oluşturur."],
"Eber Gölü":["Afyonkarahisar'da tektonik kökenli tatlı su gölüdür; Akşehir Gölü ile birbirine yakın konumdadır."],
"Çıldır Gölü":["Ardahan-Kars sınırında, Türkiye'nin en yüksek rakımlı büyük göllerinden biridir; tektonik kökenlidir ve kışın tamamen donar."],
"Hazar Gölü":["Elazığ'da, Doğu Anadolu Fay Hattı'na yakın tektonik kökenli bir göldür; net ve durgun suyuyla tatlı su turizmiyle bilinir."],
"Erçek Gölü":["Van'ın doğusunda tektonik kökenli, sodalı bir göldür; göçmen kuşlar için önemli bir sulak alandır."],
"Kovada Gölü":["Isparta'da, Göller Yöresi'nde küçük bir karstik-tektonik göldür; Kovada Gölü Milli Parkı sınırları içindedir."],
"Ege Levhası":["Ege Denizi ve çevresini kapsayan küçük levhadır.","Ege'deki gerilme (çekme) rejimi horst–graben yapısını ve graben faylarını oluşturur."]
};
