const ILLER_XY = {
"Adana":[35.33,37.0],"Adıyaman":[38.28,37.76],"Afyonkarahisar":[30.54,38.76],"Ağrı":[43.05,39.72],"Amasya":[35.83,40.65],"Ankara":[32.86,39.93],"Antalya":[30.71,36.9],"Artvin":[41.82,41.18],"Aydın":[27.84,37.85],"Balıkesir":[27.89,39.65],"Bilecik":[29.98,40.15],"Bingöl":[40.5,38.88],"Bitlis":[42.11,38.4],"Bolu":[31.61,40.73],"Burdur":[30.29,37.72],"Bursa":[29.06,40.19],"Çanakkale":[26.41,40.15],"Çankırı":[33.62,40.6],"Çorum":[34.95,40.55],"Denizli":[29.09,37.78],"Diyarbakır":[40.22,37.91],"Edirne":[26.56,41.68],"Elazığ":[39.22,38.68],"Erzincan":[39.49,39.75],"Erzurum":[41.27,39.9],"Eskişehir":[30.52,39.77],"Gaziantep":[37.38,37.06],"Giresun":[38.39,40.91],"Gümüşhane":[39.48,40.46],"Hakkâri":[43.74,37.58],"Hatay":[36.16,36.2],"Isparta":[30.55,37.76],"Mersin":[34.64,36.81],"İstanbul":[28.98,41.01],"İzmir":[27.14,38.42],"Kars":[43.09,40.6],"Kastamonu":[33.78,41.38],"Kayseri":[35.49,38.72],"Kırklareli":[27.22,41.73],"Kırşehir":[34.16,39.15],"Kocaeli":[29.92,40.77],"Konya":[32.48,37.87],"Kütahya":[29.98,39.42],"Malatya":[38.31,38.35],"Manisa":[27.43,38.61],"Kahramanmaraş":[36.93,37.58],"Mardin":[40.74,37.31],"Muğla":[28.36,37.22],"Muş":[41.49,38.74],"Nevşehir":[34.71,38.62],"Niğde":[34.68,37.97],"Ordu":[37.88,40.98],"Rize":[40.52,41.02],"Sakarya":[30.4,40.78],"Samsun":[36.33,41.29],"Siirt":[41.94,37.93],"Sinop":[35.15,42.03],"Sivas":[37.02,39.75],"Tekirdağ":[27.51,40.98],"Tokat":[36.55,40.32],"Trabzon":[39.72,41.0],"Tunceli":[39.55,39.11],"Şanlıurfa":[38.79,37.16],"Uşak":[29.41,38.68],"Van":[43.38,38.49],"Yozgat":[34.81,39.82],"Zonguldak":[31.79,41.46],"Aksaray":[34.03,38.37],"Bayburt":[40.23,40.26],"Karaman":[33.22,37.18],"Kırıkkale":[33.51,39.85],"Batman":[41.13,37.88],"Şırnak":[42.46,37.52],"Bartın":[32.34,41.64],"Ardahan":[42.7,41.11],"Iğdır":[44.04,39.92],"Yalova":[29.27,40.65],"Karabük":[32.63,41.2],"Kilis":[37.12,36.72],"Osmaniye":[36.25,37.07],"Düzce":[31.16,40.84]
};
const ILLER = Object.keys(ILLER_XY);
for (const k in ILLER_XY) if (!CITY[k]) CITY[k] = ILLER_XY[k];
const BOLGE_ILLER = {
"Marmara":["Balıkesir","Bilecik","Bursa","Çanakkale","Edirne","İstanbul","Kırklareli","Kocaeli","Sakarya","Tekirdağ","Yalova"],
"Ege":["Afyonkarahisar","Aydın","Denizli","İzmir","Kütahya","Manisa","Muğla","Uşak"],
"Akdeniz":["Adana","Antalya","Burdur","Hatay","Isparta","Kahramanmaraş","Mersin","Osmaniye"],
"Karadeniz":["Amasya","Artvin","Bartın","Bayburt","Bolu","Çorum","Düzce","Giresun","Gümüşhane","Karabük","Kastamonu","Ordu","Rize","Samsun","Sinop","Tokat","Trabzon","Zonguldak"],
"İç Anadolu":["Aksaray","Ankara","Çankırı","Eskişehir","Karaman","Kayseri","Kırıkkale","Kırşehir","Konya","Nevşehir","Niğde","Sivas","Yozgat"],
"Doğu Anadolu":["Ağrı","Ardahan","Bingöl","Bitlis","Elazığ","Erzincan","Erzurum","Hakkâri","Iğdır","Kars","Malatya","Muş","Tunceli","Van"],
"Güneydoğu Anadolu":["Adıyaman","Batman","Diyarbakır","Gaziantep","Kilis","Mardin","Siirt","Şanlıurfa","Şırnak"]
};

const REGIONS = [
["Marmara Bölgesi","Marmara","#3D6EA5"],
["Ege Bölgesi","Ege","#2F8F76"],
["Akdeniz Bölgesi","Akdeniz","#1E9DB0"],
["Karadeniz Bölgesi","Karadeniz","#4C7A3E"],
["İç Anadolu Bölgesi","İç Anadolu","#C08A2E"],
["Doğu Anadolu Bölgesi","Doğu Anadolu","#8A4FB0"],
["Güneydoğu Anadolu Bölgesi","Güneydoğu Anadolu","#C1602E"]
];


const GENERAL = {
kirik:["Kırık dağlar: yer kabuğu yan basınçla karşılaşınca sertleşmiş tabakalar kıvrılamaz, kırılır. Fay boyunca yükselen kısımlara horst, çöken kısımlara graben denir (kitap s.57).","Ege Bölgesi kırık dağların en yaygın olduğu alandır: Bakırçay, Gediz, Küçük Menderes ve Büyük Menderes grabenleri arasında Kaz, Madra, Yunt, Boz, Aydın ve Menteşe dağları horst olarak yükselmiştir.","Nur (Amanos) Dağları da kitapta kırık dağ olarak gösterilir. Dünyanın en büyük graben alanı Afrika'daki Büyük Rift Vadisi'dir."],
kivrim:["Kıvrım dağları, jeosenklinallerde biriken genç ve kalın tortul tabakaların yan basınçla kıvrılmasıyla oluşur; yüksekte kalan kısım antiklinal, alçakta kalan kısım senklinaldir.","Alp–Himalaya orojenezi III. Jeolojik Zaman'da (Tersiyer) oluşmuştur. Türkiye'deki uzantıları Kuzey Anadolu Dağları ve Toros Dağları'dır (kitap s.55).","Kitap haritasındaki kıvrım dağları: Yıldız, Samanlı, Bolu, Köroğlu, Küre, Ilgaz, Canik, Giresun, Kaçkar, Mescit, Yalnızçam, Allahuekber, Palandöken, Mercan, Tecer, Sündiken, Sultan, Dedegöl, Geyik, Bey, Bolkar, Aladağlar, Tahtalı, Güneydoğu Toroslar ve Hakkâri. Munzur ve Cudi ek olarak gösterilmiştir."],
volkanik:["Volkanik dağlar Doğu ve İç Anadolu'da yoğundur; batıda Kula volkanları Türkiye'nin en genç volkanik alanlarındandır (kitap s.57).","Kitaptaki volkanlar: Ağrı, Tendürek, Süphan, Nemrut, Karacadağ (Şanlıurfa-Diyarbakır), Erciyes, Hasan, Melendiz, Karacadağ (Konya), Karadağ (Karaman), Kula. Bingöl Dağı da KPSS'de volkanik dağ olarak geçer.","Yükselti sıralaması: Ağrı (5137 m), Süphan (4058 m), Erciyes (3917 m). Erciyes, Hasan ve Melendiz'in tüfleri Kapadokya tüf platosunu oluşturmuştur."],
fay:["Türkiye'nin ana fay hatları: Kuzey Anadolu Fay Hattı, Doğu Anadolu Fay Hattı ve Batı Anadolu Fay Zonları (kitap s.33).","KAF sağ yanal doğrultu atımlıdır, yaklaşık 1200 km'dir ve Türkiye'nin en uzun ve en tehlikeli fay hattıdır. DAF sol yanal atımlıdır, yaklaşık 500 km'dir; 2020 Elazığ ve 2023 Kahramanmaraş depremleri bu hatta olmuştur.","Batı Anadolu fay zonları genellikle normal faydır; horst–graben sistemi bu faylarla oluşmuştur. KAF ile DAF Karlıova'da birleşir."],
ova:["Kitapta ovalar oluşumlarına göre altı gruptadır (s.64-67): delta, karstik (polye), eski göl tabanı, lav örtüsü (volkanik), tektonik ve dağ eteği ovaları.","Delta ovaları: Meriç, Karasu (Sakarya), Bafra (Kızılırmak), Çarşamba (Yeşilırmak), Dikili (Bakırçay), Menemen (Gediz), Selçuk-Efes (K. Menderes), Balat (B. Menderes), Silifke (Göksu), Çukurova (Seyhan-Ceyhan), Asi.","Türkiye Alp–Himalaya kuşağında olduğu için tektonik ova bakımından çok zengindir; bu ovalar verimlidir ama deprem riski yüksektir. Ovaların yükseltisi genelde batıdan doğuya artar.","Eski göl tabanı ovası denince özellikle Konya (Ereğli) ve Aksaray ovaları; lav örtüsü ovası denince Çaldıran, Muradiye ve Malazgirt anlaşılır. Antalya Ovası traverten üzerinde biriken alüvyonların oluşturduğu kıyı ovasıdır."],
plato:["Kitapta platolar beş türe ayrılır (s.60-61): lav, karstik, tüf, aşınım düzlüğü ve yatay duruşlu tabaka düzlüğü platoları.","Lav platoları (Erzurum-Kars, Ardahan): +2000 m, soğuk, çayır ve büyükbaş hayvancılık, çernezyom topraklar. Karstik platolar (Teke, Taşeli): yerleşme ve tarım polyelerde toplanır.","Tüf platosu Kapadokya'dır (Erciyes, Hasan, Melendiz tüfleri). Aşınım düzlüğü platoları: Çatalca-Kocaeli (Türkiye'nin en alçak platosu; nüfus, kentleşme ve sanayi fazla), Safranbolu, Perşembe.","Yatay duruşlu tabaka düzlüğü platoları: Haymana, Cihanbeyli, Obruk, Bozok, Uzunyayla, Yazılıkaya (İç Anadolu) ile Gaziantep ve Şanlıurfa (GAP ile sulu tarım)."],
masif:["Masif, genellikle Paleozoyik veya daha yaşlı, metamorfik ve magmatik temel kayaçlardan oluşan, çevresindeki genç birimlere göre sert kalan yaşlı arazi parçalarıdır (kitap s.21).","Uzun süre stabil kaldıkları için deprem ve volkanizmadan görece uzaktırlar; sert oldukları için kıvrılmak yerine kırılabilirler.","Kitap haritasındaki masifler: Yıldız (Istranca), Biga, Kazdağı, Uludağ, Menderes, Saruhan-Menteşe, Zonguldak, Daday-Devrekani ve Ilgaz, Kırşehir, Sultandağları, Niğde, Akdağ, Alanya-Anamur, Amasya-Tokat, Akdağmadeni, Pulur, Malatya-Pötürge, Bitlis, Mardin-Derik."],
levha:["Türkiye; Avrasya, Afrika ve Arap levhalarının etkileşim alanındadır. Anadolu ve Ege küçük levhalardır.","Arap Levhası'nın kuzeye hareketi Anadolu Levhası'nı sıkıştırır; Anadolu Levhası batıya kaçar ve saat yönünün tersine döner.","Levha sınırları deprem ve volkanizmanın yoğun olduğu kuşaklardır."],
goller:["Kitaptaki göl türleri (s.97-101): tektonik, volkanik, karstik, karma (tektonik-karstik), buzul, heyelan set, alüvyal set, lav set, kıyı set (lagün), traverten set ve baraj gölleri.","Van Gölü karma oluşumludur: çanağı tektoniktir, Nemrut lavlarının batıyı kapatmasıyla akışı engellenmiştir. Türkiye'nin en büyük, dünyanın en büyük sodalı gölüdür; yalnızca inci kefali yaşar.","Tuz Gölü tektonik, kapalı havza gölüdür ve tuz üretiminde en önemli kaynaktır. Çıldır lav set gölüdür, fazla suları Arpaçay ile Kura'ya karışır (açık havza).","Salda 'Türkiye'nin Maldivleri' karstik göl; Bafa ve Köyceğiz alüvyal set; Terkos (Durusu) içme suyu sağlayan en büyük lagün; Otlukbeli bilinen tek traverten set gölüdür. Buzul gölleri (Kaçkar, Aladağlar, Bolkar, Cilo-Sat, Uludağ) çok küçük olduğundan haritada gösterilmemiştir."],
nehirler:["Türkiye akarsularının rejimi genelde düzensizdir; hidroelektrik potansiyeli ve aşındırma güçleri yüksektir, bol alüvyon taşırlar, ulaşıma elverişli değildir ve denge profiline ulaşmamışlardır (kitap s.93).","Havzalar: Basra (Fırat, Dicle, Zap), Akdeniz (Dalaman, Eşen, Manavgat, Köprüçay, Aksu, Göksu, Seyhan, Ceyhan, Asi), Karadeniz (Kızılırmak, Yeşilırmak, Filyos, Çoruh, Sakarya), Ege (Bakırçay, Gediz, K. Menderes, B. Menderes, Meriç), Marmara (Susurluk), Hazar (Aras, Kura).","Rejim: Aras ve Kura kar-buz suyuyla; Manavgat ve Dalaman karstik kaynaklarla (düzenli) beslenir. Seyhan, Ceyhan, Fırat, Dicle, Kızılırmak ve Yeşilırmak karma rejimlidir. Doğu Karadeniz akarsuları en düzenli rejimlidir.","Akarsu çizgileri OpenStreetMap verisinden alınmış gerçek güzergâhlardır."],
akarsular:["Kollar: Porsuk (Sakarya), Devrez ve Delice (Kızılırmak), Kelkit (Yeşilırmak), Karasu ve Murat (Fırat; Elazığ yakınında birleşip Fırat adını alır), Zap (Dicle), Harşit, Gönen ve Bartın çayları.","Fırat: Erzurum Dumlu Dağları'ndan doğan Karasu ile Ağrı'dan gelen Murat'ın birleşmesiyle oluşur; Irak'ta Dicle ile birleşip Basra Körfezi'ne dökülür (kitap s.92).","Bartın Çayı'nın denize yakın kesimi KPSS'de ulaşıma elverişli akarsu örneği olarak geçer."],
sinir:["Sınır oluşturan akarsular (kitap s.94): Meriç (Türkiye–Yunanistan), Mutludere ve Tunca (Türkiye–Bulgaristan), Arpaçay (Türkiye–Ermenistan), Aras (Türkiye–Ermenistan–Nahçıvan), Asi ve Dicle (Türkiye–Suriye), Hezil (Türkiye–Irak).","Haritada bu akarsular turuncu kesikli vurgu ile gösterilir."],
barajlar:["Baraj gölleri akarsuların önüne yapılan setlerle oluşan yapay göllerdir; enerji (HES), sulama, içme suyu, taşkın kontrolü ve balıkçılık için kullanılır (kitap s.102).","En büyük 10 baraj: Atatürk, Karakaya, Keban (Fırat), Ilısu (Dicle), Altınkaya (Kızılırmak), Birecik (Fırat), Deriner (Çoruh), Oymapınar (Manavgat), Berke (Ceyhan), Ermenek (Göksu).","Barajlar akış rejimini düzenler ama buharlaşma kaybını artırır, alüvyonu tutarak delta büyümesini yavaşlatır ve ekosistemi değiştirir."],
havza:["Akarsu havzası, bir akarsuyun ve kollarının sularını topladığı alandır. Denize ulaşan havzalar açık, ulaşamayanlar kapalı havzadır (kitap s.93).","Açık havzalar: Karadeniz (en geniş açık havza), Marmara, Ege, Akdeniz, Basra Körfezi. Kapalı havzalar: Van Gölü, Tuz Gölü, Göller Yöresi ve Hazar (Aras-Kura Türkiye dışında birleşip Hazar'a ulaşır).","Havzanın kapalı olmasında bölgenin karstik yapısı ve dış drenaj bağlantısının olmaması etkilidir."],
toprak:["Toprak tipleri (kitap s.111): zonal (laterit, terra rossa, kahverengi orman, kestane rengi ve kahverengi bozkır, podzol, çernezyom, çöl, tundra), intrazonal (hidromorfik, halomorfik, kalsimorfik: vertisol ve rendzina) ve azonal (alüvyal, lös, moren, kolüvyal, litosol, regosol).","Terra rossa Türkiye'de en yaygın zonal topraktır; Akdeniz ikliminde kalkerli ana kaya üzerinde oluşur (zeytin, turunçgil, bağ). Asidik kahverengi orman toprakları nemli Karadeniz'de, kireçli orman toprakları yağışın azaldığı iç kesim ormanlarında görülür.","Çernezyom dünyanın en verimli topraklarındandır; Türkiye'de Erzurum-Kars Platosu'nda çayırlar altında görülür. Bozkır toprakları İç, Güneydoğu ve Doğu Anadolu'da; alüvyal topraklar Çukurova, Bafra, Çarşamba, Gediz ve Sakarya ovalarında yaygındır.","Haritada gösterilmeyenler: halomorfik (Tuz Gölü çevresi, Konya ve Iğdır ovaları), hidromorfik (bataklık ovalar), lös (İç Anadolu'da sınırlı), moren (Kaçkar, Cilo-Sat, Aladağlar, Ağrı, Erciyes, Süphan, Munzur), kolüvyal (dağ etekleri). Türkiye'de gerçek podzol, laterit, çöl ve tundra toprağı yoktur."],
deprem:["Kitaptaki deprem bölgeleri haritası (s.33) beş derecelidir: 1. derece çok şiddetli ve yıkıcı, 5. derece hafif şiddetli depremler.","1. derece bölgeler KAF, DAF ve Ege graben fayları boyunca uzanır. Tehlikenin en az olduğu alanlar Konya-Karaman çevresi ile Kırşehir'in iç kesimleridir.","Not: Bu harita kitaptaki eski derecelendirmeyi gösterir; güncel resmi haritada (2018) dereceler yerine yer ivmesi değerleri kullanılmaktadır."],
bolge:["Türkiye, 1941'de toplanan I. Coğrafya Kongresi'nde iklim, bitki örtüsü, tarım ürünleri, yeryüzü şekilleri ve ulaşım gibi ölçütler kullanılarak 7 coğrafi bölgeye ayrılmıştır: Marmara, Ege, Akdeniz, Karadeniz, İç Anadolu, Doğu Anadolu, Güneydoğu Anadolu.","KPSS'de sık karıştırılan konu: bu 7 bölge \"coğrafi bölge\"dir; ayrıca AB'ye uyum için oluşturulan İBBS (İstatistiki Bölge Birimleri Sınıflandırması) vardır: Düzey 1'de 12 bölge, Düzey 2'de 26 alt bölge, Düzey 3'te 81 il yer alır.","Yüzölçümü büyüklük sırası (büyükten küçüğe): Doğu Anadolu, İç Anadolu, Akdeniz, Ege, Karadeniz, Marmara, Güneydoğu Anadolu.","Nüfus yoğunluğu en fazla bölge Marmara'dır (sanayi ve hizmet sektörü yoğun); nüfus yoğunluğu en az bölge Doğu Anadolu'dur."],
komsu:["Türkiye'nin kara sınırı bulunan 8 komşusu vardır: Yunanistan, Bulgaristan, Gürcistan, Ermenistan, Azerbaycan (Nahçıvan dahil), İran, Irak ve Suriye.","Batıda Yunanistan ve Bulgaristan; doğuda Gürcistan, Ermenistan, Azerbaycan ve İran; güneyde Irak ve Suriye bulunur.","Kara sınırlarının uzunlukları kıyı ve sınır düzenlemelerine göre kaynaklarda farklı yuvarlanabilir; bu harita ülke adlarını ve gerçek Natural Earth sınır geometrilerini gösterir, kesin kilometre sıralaması iddiası taşımaz."],
iller:["Türkiye'de 81 il vardır. Bölgelere göre dağılım: Karadeniz 18, İç Anadolu 13, Doğu Anadolu 14, Marmara 11, Güneydoğu Anadolu 9, Ege 8, Akdeniz 8.","En çok ile sahip bölge Karadeniz'dir; en az ile sahip bölgeler Ege ve Akdeniz'dir (8'er il).","İstanbul ve Çanakkale iki kıtada toprağı olan illerdir (Avrupa ve Asya)."]
};

const NOTES = {
"Kaz Dağları":["Balıkesir ve Çanakkale arasında, Edremit Körfezi'nin kuzeyindedir; antik çağda İda Dağı olarak anılırdı.","Kazdağ Masifi'nin kırılmasıyla oluşan kırık (horst) dağdır; en yüksek noktası Karataş Tepesi'dir (yaklaşık 1774 m).","Kaz Dağları Milli Parkı ve endemik Kazdağı göknarıyla bilinir."],
"Madra Dağı":["Ege'nin kuzeyinde yer alan Ege kırık dağlarından biridir.","Sınavlarda Kaz, Madra, Yunt, Bozdağlar, Aydın ve Menteşe dağları birlikte Ege'nin kırık dağları olarak sorulur."],
"Yunt Dağı":["Manisa yöresinde yer alan, Ege kırık (horst) dağlarından biridir.","Ege kırık dağları grubuyla birlikte hatırlayın: Kaz, Madra, Yunt, Bozdağlar, Aydın, Menteşe."],
"Bozdağlar":["Gediz ve Küçük Menderes grabenleri arasında uzanan kırık (horst) dağdır.","En yüksek noktası Bozdağ'dır (yaklaşık 2159 m); Menderes Masifi'nin bir parçasıdır."],
"Aydın Dağları":["Küçük Menderes ve Büyük Menderes grabenleri arasındaki horst'tur.","Menderes Masifi'nin bir parçası olduğu için hem masif hem kırık dağ örneği olarak sorulur."],
"Menteşe Dağları":["Muğla çevresinde, Ege Bölgesi'nin güney kesiminde yer alan kırık (horst) dağdır; adını Muğla'nın Menteşe ilçesinden alır.","Ege kırık dağları arasında sayılır: Kaz, Madra, Yunt, Bozdağlar, Aydın, Menteşe."],
"Nur (Amanos) Dağları":["Hatay ve Osmaniye çevresinde, Akdeniz kıyısına paralel uzanır; kırık dağ olarak sınıflandırılır.","Belen Geçidi bu dağlardan geçer ve Akdeniz'i Suriye'ye bağlayan önemli bir geçittir.","Amik Ovası ile Akdeniz arasında yer alır."],
"Bakırçay Grabeni":["Bakırçay Ovası'nın içinde uzanan Ege çöküntü alanıdır.","Kaynakta Kaz, Madra ve Yunt horstlarıyla birlikte Ege'nin kırık dağ-graben sisteminin bir parçası olarak gösterilir."],
"Gediz Grabeni":["Manisa ve Alaşehir çevresinde doğu-batı doğrultusunda uzanan çöküntü alanıdır.","Gediz Ovası bu grabenin tabanında yer alır; Bozdağlar ve Yunt Dağı çevredeki horst örnekleridir."],
"Küçük Menderes Grabeni":["Ödemiş, Tire ve Selçuk çevresinde uzanan Ege çöküntü alanıdır.","Bozdağlar ile Aydın Dağları arasındaki graben sisteminin parçasıdır."],
"Büyük Menderes Grabeni":["Denizli, Nazilli, Aydın ve Söke boyunca uzanan geniş çöküntü alanıdır.","Büyük Menderes Ovası graben tabanında gelişmiştir; Aydın Dağları çevredeki horst örneklerindendir."],
"Samanlı Dağları":["Marmara Bölgesi'nde, İznik Gölü ile Marmara kıyısı arasında (Yalova, Kocaeli, Bursa çevresi) uzanan kıvrım dağıdır.","Marmara'daki dağlar sorulurken Uludağ ve Istranca masif, Samanlı ise kıvrım dağı olarak ayrılır."],
"Bey Dağları":["Antalya'nın batısında Batı Toroslar'ın bir parçasıdır (Teke Yöresi).","Batı Toroslar: Beydağları, Akdağ, Katrancık gibi dağlardan oluşur."],
"Geyik Dağları":["Orta Toroslar içinde, Antalya, Konya ve Karaman yöresinde yer alır.","Orta Toroslar'ın ana dağları: Geyik Dağları, Bolkar Dağları, Aladağlar."],
"Bolkar Dağları":["Orta Toroslar'da, Niğde, Mersin ve Karaman çevresindedir; en yüksek noktası Medetsiz Tepesi'dir (yaklaşık 3524 m).","Bolkar Dağları ile Aladağlar arasında Ecemiş Fayı ve koridoru bulunur."],
"Aladağlar":["Niğde, Adana ve Kayseri arasında Orta Toroslar'dadır; en yüksek zirvesi Demirkazık Tepesi'dir (3756 m).","Aladağlar Milli Parkı; dağcılık ve doğa sporlarıyla bilinir."],
"Munzur Dağları":["Tunceli ve Erzincan arasında, Doğu Anadolu Bölgesi'nde yer alır.","Munzur Suyu bu dağlardan doğar ve Fırat'a karışır; Munzur Vadisi Milli Parkı buradadır."],
"Mercan Dağları":["Erzincan çevresinde, Doğu Anadolu'daki kıvrım dağlarındandır.","Doğu Anadolu'nun kıvrım dağları (Munzur, Mercan, Palandöken, Allahuekber) birlikte sorulur."],
"Cudi Dağı":["Şırnak'ta, Güneydoğu Toroslar üzerinde yer alır.","Nuh'un Gemisi rivayetlerinde Cudi Dağı'na atıf yapılır (Ağrı Dağı ile karıştırılmamalı)."],
"Hakkâri Dağları":["Cilo ve Sat Dağları bu kuşaktadır; Cilo'daki Uludoruk Tepesi (4135 m) Türkiye'nin volkanik olmayan en yüksek zirvesidir.","Güneydoğu Toroslar'ın doğu ucudur; Türkiye'de buzulların görüldüğü dağlar arasındadır."],
"Köroğlu Dağları":["Bolu, Ankara ve Çankırı arasında, Batı Karadeniz'de Kuzey Anadolu Dağları'nın bir parçasıdır.","Bolu Dağı geçidi (TEM otoyolu ve Bolu Dağı Tüneli) bu kuşaktadır."],
"Ilgaz Dağları":["Kastamonu ve Çankırı arasındadır; Ilgaz Dağı Milli Parkı ve kayak merkeziyle bilinir.","En yüksek noktası Büyük Hacet Tepesi'dir (yaklaşık 2587 m)."],
"Küre Dağları":["Kastamonu ve Bartın çevresinde, Batı Karadeniz'de Karadeniz kıyısına paralel uzanır.","Küre Dağları Milli Parkı ve Küre'deki bakır yatakları ile bilinir."],
"Canik Dağları":["Samsun ve Ordu arasında, Orta Karadeniz'de Kuzey Anadolu Dağları'nın parçasıdır.","Karadeniz'e paralel uzanan bu dağlar, iç kesime nem girişini sınırlar."],
"Kaçkar Dağları":["Rize, Artvin ve Erzurum arasında yer alır; en yüksek noktası Kaçkar Dağı'dır (3937 m), Kuzey Anadolu Dağları'nın en yükseğidir.","Yaylalar ve buzul gölleri ile bilinir; Rize Türkiye'nin en fazla yağış alan ilidir."],
"Yalnızçam Dağları":["Ardahan ve Artvin arasında, Doğu Karadeniz Dağları'nın kuzeydoğu uzantısıdır.","Yalnızçam Dağları'nda kayak turizmi (Ardahan) ve sert kışlar dikkat çeker."],
"Allahuekber Dağları":["Erzurum ve Kars arasında, Sarıkamış yöresindedir.","1914–1915 Sarıkamış Harekâtı ve Sarıkamış kayak merkezi ile bilinir."],
"Palandöken Dağları":["Erzurum'un güneyinde yer alır; kış sporları ve kayak merkeziyle bilinir.","Türkiye'nin başlıca kayak merkezleri: Palandöken (Erzurum), Erciyes (Kayseri), Uludağ (Bursa), Kartalkaya (Bolu), Sarıkamış (Kars)."],
"Ağrı Dağı":["5137 m ile Türkiye'nin en yüksek dağıdır; Ağrı ve Iğdır arasında yer alan sönmüş bir volkandır.","Sürekli karlı ve buzulludur; yanındaki Küçük Ağrı 3896 m'dir.","Nuh'un Gemisi rivayetleriyle anılır."],
"Tendürek Dağı":["Ağrı ve Doğubayazıt çevresinde, Doğu Anadolu'da yer alır; yaklaşık 3533 m.","Türkiye'de tamamen sönmemiş, fümerol etkinliği gösteren volkanlardan biridir."],
"Süphan Dağı":["Bitlis'in Adilcevaz ilçesi yakınında, Van Gölü'nün kuzeyindedir (4058 m).","Türkiye'nin Ağrı'dan sonra en yüksek ikinci volkanik dağıdır."],
"Nemrut Dağı":["Bitlis'in Tatvan ilçesinde, Van Gölü'nün batı ucundadır; krater gölüyle bilinir.","Nemrut lavlarının tektonik çanağın batısını kapatmasıyla Van Gölü oluşmuştur (kitapta karma oluşumlu göl).","Adıyaman'daki Nemrut Dağı (heykelleri ve kral mezarı) farklı bir dağdır; ikisi karıştırılmamalı."],
"Bingöl Dağı":["Bingöl çevresinde, Doğu Anadolu'da yer alan volkanik dağdır (yaklaşık 3258 m).","Doğu Anadolu'daki volkanik dağlar: Ağrı, Tendürek, Süphan, Nemrut, Bingöl."],
"Karacadağ (Şanlıurfa)":["Diyarbakır ve Şanlıurfa arasında, Güneydoğu Anadolu'daki geniş lav (bazalt) platosudur.","Karacadağ pirinci (Diyarbakır) coğrafi işaretli ürünler arasında sayılır."],
"Erciyes Dağı":["Kayseri'de yer alır; 3917 m ile İç Anadolu'nun en yüksek dağıdır (sönmüş volkan).","Kış turizmi ve Kapadokya'daki tüf oluşumuyla ilişkilendirilir."],
"Hasan Dağı":["Aksaray'da, Tuz Gölü'nün güneydoğusunda yer alır; yaklaşık 3253 m, çift tepelidir.","Kapadokya'nın tüf ve peribacası oluşumuna katkıda bulunan volkanlardandır."],
"Melendiz Dağı":["Aksaray ve Niğde arasında yer alan volkanik dağdır.","Melendiz Çayı, Ihlara Vadisi'ni açmıştır."],
"Karadağ (Karaman)":["Karaman'da, Konya Ovası'nın güneyinde yer alan volkanik koni dağıdır.","Binbir Kilise kalıntıları Karadağ eteklerindedir."],
"Kula Volkanları":["Manisa'nın Kula ilçesinde yer alır; Türkiye'nin en genç volkanik alanlarından biridir.","Kula–Salihli Jeoparkı, UNESCO Küresel Jeoparklar Ağı üyesidir."],
"Kuzey Anadolu Fay Hattı":["Bingöl-Karlıova'dan Marmara Denizi'ni geçerek Saros Körfezi'ne kadar yaklaşık 1200 km uzanır (kitap s.33); sağ yanal doğrultu atımlı fay hattıdır.","Avrasya ve Anadolu levhalarının sınırıdır.","Bilinen depremler: 1939 Erzincan (7.9), 1999 İzmit/Marmara (7.4) ve Düzce (7.2).","Türkiye'nin en aktif ve en çok bilinen fay hattıdır."],
"Doğu Anadolu Fay Hattı":["Karlıova'dan Hatay'ın güneyine kadar yaklaşık 500 km uzanır; sol yanal doğrultu atımlıdır.","Anadolu ve Arap levhalarının sınırıdır.","Bilinen depremler: 2020 Elazığ Sivrice (6.8) ve 6 Şubat 2023 Kahramanmaraş depremleri (Pazarcık merkezli 7.7, Elbistan merkezli 7.6; AFAD)."],
"Gediz Grabeni Fayı":["Alaşehir, Salihli ve Manisa boyunca uzanır; batıda İzmir Körfezi'ne ulaşan Gediz Nehri çevresindeki graben ovasını oluşturur.","Ege'de doğu–batı uzanan çekme (normal) faylardan biridir."],
"Büyük Menderes Grabeni Fayı":["Denizli, Nazilli, Aydın ve Söke çizgisi boyunca uzanır.","Büyük Menderes Nehri graben tabanından akar ve Ege Denizi'ne dökülür; Pamukkale travertenleri Denizli çevresindedir."],
"Küçük Menderes Grabeni Fayı":["Ödemiş, Tire ve Selçuk yöresinden geçer; Küçük Menderes Nehri graben tabanından akar.","Bozdağlar ile Aydın Dağları arasındaki graben bu hat üzerindedir."],
"Fethiye–Burdur Fay Zonu":["Batı Toroslar'da Fethiye'den Burdur'a uzanan KD–GB doğrultulu fay zonudur.","1971 Burdur depremi (6.2) ve 1957 Fethiye depremi bu bölgede yaşanmıştır."],
"Tuz Gölü Fayı":["Şereflikoçhisar ile Aksaray arasında Tuz Gölü çukurunu sınırlayan fay zonudur.","Tuz Gölü, tektonik çukurlukta oluşmuş bir göldür; Van Gölü'nden sonra Türkiye'nin ikinci büyük gölüdür ve tuz üretimi için önemlidir."],
"Ecemiş Fayı":["Orta Toroslar'da Pozantı, Çamardı ve Yahyalı çizgisinde uzanır.","Bolkar Dağları ile Aladağlar'ı ayıran Ecemiş Koridoru bu fay boyunca uzanır."],
"Yunanistan":["Türkiye'nin batısında, Ege ve Trakya üzerinden kara komşusudur.","Edirne ve Meriç Nehri çevresindeki kara sınırı Türkiye'nin batı komşuluk kuşağındadır."],
"Bulgaristan":["Türkiye'nin kuzeybatısında, Trakya üzerinden kara komşusudur.","Kırklareli ve Edirne çevresi Bulgaristan sınır kuşağında yer alır."],
"Gürcistan":["Türkiye'nin kuzeydoğusunda, Artvin ve Ardahan çevresinden kara komşusudur.","Doğu Karadeniz'in doğu kesiminde yer alır."],
"Ermenistan":["Türkiye'nin doğusunda, Kars ve Iğdır çevresinden kara komşusudur.","Sınır kuşağı Doğu Anadolu'nun kuzeydoğu kesimindedir."],
"Azerbaycan (Nahçıvan dahil)":["Türkiye'nin doğusunda Nahçıvan Özerk Cumhuriyeti üzerinden kısa bir kara sınırı vardır.","Bu nedenle Azerbaycan, ana karası Türkiye'ye bitişik olmasa da Türkiye'nin kara komşuları arasında sayılır."],
"İran":["Türkiye'nin doğusunda, Doğu Anadolu'nun doğu ve güneydoğu kuşağından kara komşusudur.","Van, Ağrı ve Hakkâri çevreleri İran sınır kuşağıyla ilişkilidir."],
"Irak":["Türkiye'nin güneydoğusunda, Hakkâri ve Şırnak çevresinden kara komşusudur.","Sınır kuşağı Güneydoğu Toroslar'ın doğu bölümüne yakın uzanır."],
"Suriye":["Türkiye'nin güneyinde, Akdeniz ve Güneydoğu Anadolu boyunca kara komşusudur.","Hatay, Kilis, Gaziantep, Şanlıurfa, Mardin ve Şırnak çevreleri Suriye sınır kuşağındadır."],
"Avrasya Levhası":["Türkiye'nin kuzeyinde; KAF ile Anadolu Levhası'ndan ayrılır.","Karadeniz'in altı Avrasya Levhası üzerindedir."],
"Anadolu Levhası":["Türkiye'nin büyük bölümünü kapsayan küçük levhadır.","Arap Levhası'nın kuzeye hareketiyle sıkışır, batıya kaçar ve saat yönünün tersine döner.","Sınırları: KAF (kuzey), DAF (doğu/güneydoğu)."],
"Arap Levhası":["Güneydoğuda yer alır; kuzeye hareket ederek Anadolu ve Avrasya levhalarına sıkışır.","DAF, Anadolu ile Arap levhası arasındaki sınırdır; Bitlis–Zagros kenet kuşağı ile ilişkilidir."],
"Afrika Levhası":["Türkiye'nin güneyinde, Akdeniz tabanında yer alır.","Girit–Kıbrıs yayları boyunca Anadolu ve Ege levhalarının altına dalar."],
"Marmara Bölgesi":["Yüzölçümü en küçük ikinci bölgedir fakat nüfusça en kalabalık ve nüfus yoğunluğu en fazla bölgedir.","Sanayi, ticaret ve hizmet sektörünün en gelişmiş olduğu bölgedir; tarım alanlarının payı diğer bölgelere göre azdır.","Karadeniz ile Ege/Akdeniz arasında geçiş konumundadır; İstanbul ve Çanakkale boğazlarıyla Asya ve Avrupa'yı birbirine bağlar."],
"Ege Bölgesi":["Kıyı çizgisi girinti çıkıntısı en fazla olan bölgedir (Ege tipi/enine kıyı); dağlar kıyıya dik uzanır.","Kırık (horst-graben) dağların tipik görüldüğü bölgedir; zeytin, tütün, incir, üzüm ve pamuk üretiminde önde gelir.","İzmir bölgenin nüfus ve sanayi bakımından en büyük ilidir."],
"Akdeniz Bölgesi":["Toroslar kıyıya paralel uzanır; kıyı ile iç kesim arasında iklim ve bitki örtüsü farkı belirgindir.","Turunçgil, muz ve seracılıkta (özellikle Antalya) Türkiye'nin önde gelen bölgesidir.","Çukurova, bölgenin ve Türkiye'nin en büyük delta ovasıdır."],
"Karadeniz Bölgesi":["Türkiye'nin en fazla yağış alan bölgesidir; her mevsim yağışlı ılıman iklim görülür.","En fazla ile sahip bölgedir (18 il); dağların kıyıya paralel uzanması iç kesimlerle ulaşımı zorlaştırır.","Çay (Rize/Doğu Karadeniz) ve fındık (Orta/Batı Karadeniz) üretiminde Türkiye'de birinci bölgedir."],
"İç Anadolu Bölgesi":["Yüzölçümü bakımından ikinci büyük bölgedir; karasal iklim ve step (bozkır) bitki örtüsü egemendir.","Tahıl (özellikle buğday) üretiminde Türkiye'nin ambarı kabul edilir; hayvancılıkta küçükbaş önemlidir.","Başkent Ankara bu bölgededir; kırık ve volkanik dağlar ile geniş ova/platolar bir arada görülür."],
"Doğu Anadolu Bölgesi":["Yüzölçümü en büyük bölgedir; ortalama yükseltisi de Türkiye'de en fazladır.","Kışları en sert ve en uzun süren bölgedir; nüfus yoğunluğu en düşük bölgelerdendir.","Büyükbaş hayvancılık (özellikle sığır) önemlidir; volkanik dağlar (Ağrı, Süphan, Nemrut) ve yüksek ovalar/platolar (Erzurum-Kars) tipiktir."],
"Güneydoğu Anadolu Bölgesi":["Yüzölçümü en küçük bölgedir; Suriye sınırı boyunca uzanır.","Karasal iklime yakın, sıcak ve kurak yazlar görülür; GAP (Güneydoğu Anadolu Projesi) barajlarıyla sulu tarım alanı genişlemiştir.","Antepfıstığı, pamuk ve zeytin üretiminde öne çıkar; Harran Ovası GAP'ın simge tarım alanlarındandır."],
"Ege Levhası":["Ege Denizi ve çevresini kapsayan küçük levhadır.","Ege'deki gerilme (çekme) rejimi horst–graben yapısını ve graben faylarını oluşturur."],
"Karacadağ (Konya)":["Konya'nın Karapınar çevresindeki volkanik sahadadır; kitapta Hasan ve Melendiz'in güneybatısında gösterilir.","Karapınar yöresindeki Meke ve Acıgöl maar gölleri aynı volkanik alandadır."],
"Yıldız Dağları":["Trakya'nın kuzeyinde, Kırklareli çevresinde Karadeniz kıyısına paralel uzanan kıvrım dağıdır.","Yıldız (Istranca) Masifi ile aynı alandadır; masif ve kıvrım olarak ayrı sorulabilir."],
"Bolu Dağları":["Bolu ile Düzce arasında, Kuzey Anadolu Dağları'nın batı kesiminde yer alan kıvrım dağıdır.","Kuzey Anadolu Fay Hattı bu dağların güneyinden geçer."],
"Giresun Dağları":["Doğu Karadeniz'de kıyıya paralel uzanan Kuzey Anadolu Dağları'nın parçasıdır.","Kıyıya paralel dağlar nedeniyle Karadeniz kıyılarında boyuna kıyı tipi görülür."],
"Mescit Dağları":["Erzurum'un kuzeyinde, Çoruh vadisi ile Erzurum-Kars yöresi arasında uzanan kıvrım dağıdır.","Karasu (Fırat) ve Çoruh'un kaynak alanlarına yakındır."],
"Tecer Dağları":["Sivas'ın güneyinde, Kızılırmak havzası ile Fırat havzası arasında uzanan kıvrım dağıdır.","Toroslar ile Kuzey Anadolu Dağları'nın birbirine yaklaştığı kesimdedir."],
"Sündiken Dağları":["Eskişehir'in kuzeyinde, Sakarya ve Porsuk vadileri arasında uzanan kıvrım dağıdır.","Kitap haritasında İç Anadolu'nun kuzeybatısında gösterilir."],
"Sultan Dağları":["Afyonkarahisar, Isparta ve Konya arasında, Akşehir ve Eber göllerinin güneybatısında uzanır.","Batı Toroslar'ın kuzey uzantısıdır; Sultandağları Masifi ile karıştırılmamalıdır."],
"Dedegöl Dağları":["Beyşehir ile Eğirdir gölleri arasında, Göller Yöresi'nde uzanan Batı Toros kıvrım dağıdır.","Çevresinde karstik şekiller ve polyeler yaygındır."],
"Tahtalı Dağları":["Kayseri'nin güneydoğusunda, Aladağlar'ın kuzeydoğusunda uzanan Orta Toros kıvrım dağıdır.","Toroslar burada kuzeydoğuya yönelerek Güneydoğu Toroslar'a bağlanır."],
"Güneydoğu Toroslar":["Kahramanmaraş'tan Hakkâri'ye kadar yay çizerek uzanan Toros kıvrım kuşağının doğu kesimidir.","Güneydoğu Anadolu'yu Doğu Anadolu'dan ayırır; doğu ucunda Hakkâri Dağları yer alır."],
"Çatalca-Kocaeli Platosu":["Aşınım düzlüğü platosudur; uzun süre aşınıp peneplenleşen yüzeyin tektonik yükselme sonrası akarsularca yarılmasıyla oluşmuştur.","Türkiye'nin en alçak platosudur; nüfus yoğunluğu fazla, kentleşme ve sanayi gelişmiş, tarım alanları sınırlıdır."],
"Safranbolu Platosu":["Batı Karadeniz'de, Karabük çevresindeki aşınım düzlüğü platosudur.","Kitapta Çatalca-Kocaeli ve Perşembe ile birlikte aşınım platoları arasında sayılır."],
"Perşembe Platosu":["Ordu çevresinde, Doğu Karadeniz kıyı dağlarının gerisindeki aşınım düzlüğü platosudur.","Yayla hayvancılığı ve yayla turizmiyle bilinir."],
"Teke Platosu":["Batı Toroslar'da (Antalya-Burdur-Muğla arası) kalker üzerinde gelişmiş karstik platodur.","Yerleşmeler ve tarım polyelerde toplanmıştır; sulama zordur."],
"Taşeli Platosu":["Orta Toroslar'da, Göksu vadisi ile Akdeniz arasında (Mersin-Karaman) yer alan karstik platodur.","Yüzey suyu azdır; dolin, uvala ve polye gibi karstik şekiller yaygındır."],
"Erzurum-Kars Platosu":["Volkanik lavların geniş alanlara yayılıp akarsularca parçalanmasıyla oluşan lav platosudur; yükseltisi genelde 2000 m'nin üzerindedir.","Sert karasal iklim; çayırlar ve büyükbaş mera hayvancılığı yaygındır, nüfus yoğunluğu azdır. Çernezyom toprakları bu platoda görülür."],
"Ardahan Platosu":["Kitapta Erzurum-Kars ile birlikte lav platosu olarak gösterilir.","Soğuk ve kısa yazlı iklim nedeniyle tarım ürün çeşitliliği az, büyükbaş hayvancılık ön plandadır."],
"Kapadokya Platosu":["Erciyes, Hasan ve Melendiz volkanlarından çıkan tüflerin akarsularla parçalanmasıyla oluşan tüf platosudur.","Topraklar verimlidir; üzüm bağcılığı ve patates yaygındır. Peribacaları, kiliseler ve yeraltı şehirleriyle önemli bir turizm alanıdır."],
"Yazılıkaya Platosu":["Eskişehir-Afyonkarahisar-Kütahya arasındaki yatay duruşlu tabaka düzlüğü platosudur.","Frig vadisi ve kaya anıtlarıyla bilinir."],
"Haymana Platosu":["Ankara'nın güneybatısında yatay duruşlu tabaka düzlüğü platosudur.","İç Anadolu platolarında sulama yetersiz olduğundan kuru tarım (tahıl) ve küçükbaş hayvancılık yapılır."],
"Cihanbeyli Platosu":["Tuz Gölü'nün batısında, Konya'nın kuzeyinde yatay duruşlu tabaka platosudur.","Kuru tarım ve küçükbaş hayvancılık yaygındır; nüfus yoğunluğu düşüktür."],
"Obruk Platosu":["Konya ile Aksaray arasında yatay duruşlu tabaka platosudur.","Obruk adı verilen karstik çöküntü çukurlarıyla bilinir; küçük karstik çanaklar görülür."],
"Bozok Platosu":["Yozgat çevresinde yatay duruşlu tabaka düzlüğü platosudur.","Tahıl tarımı ve küçükbaş hayvancılık yaygındır."],
"Uzunyayla Platosu":["Sivas ile Kayseri arasında yatay duruşlu tabaka platosudur.","Uzunyayla atları ve mera hayvancılığıyla bilinir."],
"Gaziantep Platosu":["Güneydoğu Anadolu'da yatay duruşlu tabaka düzlüğü platosudur.","GAP ile sulama geliştiği için pamuk, mısır, sebze-meyve üretimi artmıştır; antepfıstığı ve zeytin önemlidir."],
"Şanlıurfa Platosu":["Güneydoğu Anadolu'da yatay duruşlu tabaka düzlüğü platosudur.","GAP ile sulamalı tarım gelişmiş, nüfus artmıştır; son yıllarda büyükbaş hayvancılık da gelişmektedir."],
"Çukurova":["Seyhan ve Ceyhan nehirlerinin taşıdığı alüvyonlarla oluşan delta ovasıdır; Türkiye'nin en büyük delta ovasıdır.","Alüvyal topraklar ve sulama sayesinde pamuk, narenciye, mısır ve soya üretimi yüksektir."],
"Bafra Ovası":["Kızılırmak'ın taşıdığı alüvyonlarla oluşmuş delta ovasıdır (Samsun).","Alüvyal toprakların en geniş yayıldığı ovalardandır; tütün, çeltik ve sebze yetiştirilir."],
"Çarşamba Ovası":["Yeşilırmak'ın alüvyonlarıyla oluşmuş delta ovasıdır (Samsun).","Fındık, mısır, çeltik ve sebze üretimi yaygındır."],
"Karasu (Sakarya) Deltası":["Sakarya Nehri'nin Karadeniz'e döküldüğü yerde oluşan delta ovasıdır."],
"Meriç Deltası":["Meriç Nehri'nin Ege Denizi'ne döküldüğü Enez çevresindeki delta ovasıdır.","Meriç aynı zamanda Türkiye–Yunanistan sınırını oluşturur."],
"Dikili Ovası":["Bakırçay'ın alüvyonlarıyla oluşan delta ovasıdır (Çandarlı Körfezi)."],
"Menemen Ovası":["Gediz Nehri'nin alüvyonlarıyla oluşan delta ovasıdır (Foça yakınları)."],
"Selçuk-Efes Ovası":["Küçük Menderes'in alüvyonlarıyla oluşan delta ovasıdır; antik Efes limanı alüvyonla dolmuştur."],
"Balat Ovası":["Büyük Menderes'in alüvyonlarıyla oluşan delta ovasıdır; Bafa Gölü bu alüvyonların Latmos Körfezi'ni kapatmasıyla oluşmuştur."],
"Silifke Ovası":["Göksu Nehri'nin alüvyonlarıyla oluşan delta ovasıdır; Göksu Deltası Ramsar alanıdır."],
"Asi Deltası":["Asi Nehri'nin Samandağ'da Akdeniz'e döküldüğü yerdeki delta ovasıdır."],
"Konya-Ereğli Ovası":["Kitapta eski göl tabanı ovası olarak gösterilir: tektonik çanaktaki gölün kuruması veya sularının çekilmesiyle oluşmuştur.","Tabanında alüvyal ve kısmen tuzlu topraklar bulunur; Türkiye'nin en büyük ovası Konya Ovası'dır."],
"Aksaray Ovası":["Eski göl tabanı ovasıdır; Tuz Gölü'nün güneydoğusundadır.","Tabanda alüvyal ve kısmen tuzlu topraklar görülür."],
"Malazgirt Ovası":["Lav örtüsü (volkanik) ovasıdır: lavların tektonik çukurlukları doldurmasıyla oluşan geniş düzlüktür.","Topraklar mineralce zengin olduğundan tarıma elverişlidir."],
"Çaldıran Ovası":["Van'ın kuzeydoğusunda lav örtüsü ovasıdır."],
"Muradiye Ovası":["Van Gölü'nün kuzeydoğusunda lav örtüsü ovasıdır."],
"Muğla Polyesi":["Göller Yöresi–Teke yöresindeki karstik ovalardan (polye) biridir; kalker ve jips gibi eriyebilen kayaçlarda çözünme ile oluşan geniş çanaklardır."],
"Elmalı Polyesi":["Antalya'nın batısında karstik ova (polye); Avlan Gölü bu ovadadır."],
"Kestel Polyesi":["Burdur-Bucak yöresinde karstik ova (polye)."],
"Korkuteli Polyesi":["Antalya'nın kuzeybatısında karstik ova (polye)."],
"Acıpayam Polyesi":["Denizli'nin güneyinde karstik ova (polye)."],
"Tefenni Polyesi":["Burdur'un güneybatısında karstik ova (polye)."],
"Burdur Ovası (Polye)":["Kitapta karstik ovalar arasında sayılır; Burdur Gölü çevresindedir."],
"Bursa Ovası":["Tektonik kökenlidir; kenarında Uludağ'dan inen akarsuların oluşturduğu dağ eteği birikintileri de vardır.","Sanayi ve kentleşme nedeniyle tarım alanları daralmaktadır."],
"Bursa Ovası (dağ eteği)":["Uludağ eteklerinde dağ eteği ovası; kitapta tektonik ovalarla iç içe gelişen dağ eteği ovası örneğidir."],
"Isparta Ovası":["Davraz Dağı eteklerinde oluşmuş dağ eteği ovasıdır; gül üretimiyle bilinir."],
"Kayseri Ovası":["Erciyes Dağı eteklerinde oluşmuş dağ eteği ovasıdır."],
"Ergene Ovası":["Trakya'da, Ergene Nehri boyunca uzanan tektonik ovadır; ayçiçeği ve buğday üretimi yüksektir."],
"Adapazarı Ovası":["Kuzey Anadolu Fay Hattı üzerindeki tektonik ovadır; 1999 depreminden etkilenmiştir."],
"Harran Ovası":["Şanlıurfa'da tektonik ovadır; GAP ve Şanlıurfa Tünelleri ile sulanarak pamuk üretiminin merkezi olmuştur."],
"Amik Ovası":["Hatay'da tektonik ovadır; eski Amik Gölü kurutularak tarım alanı kazanılmıştır.","Kitapta Kahramanmaraş'a uzanan tektonik oluk içinde gösterilir."],
"Muş Ovası":["Doğu Anadolu'da tektonik ovadır; Murat Nehri buradan geçer."],
"Erzincan Ovası":["Kuzey Anadolu Fay Hattı üzerinde tektonik ovadır; 1939 Erzincan depremiyle bilinir."],
"Erzurum Ovası":["Kitaba göre tektonik kökenli çöküntü havzasıdır; volkanik ürünlerle çevrili olduğundan tabanı alüvyonla dolmuş taşkın ovası niteliği taşır."],
"Iğdır Ovası":["Aras Nehri boyunca uzanan tektonik ovadır; Doğu Anadolu'nun en alçak ve en sıcak ovasıdır, pamuk yetişebilir.","Kitaba göre halomorfik (tuzlu) topraklar da görülür."],
"Yıldız (Istranca) Masifi":["Trakya'nın kuzeyinde, Kırklareli çevresindeki Paleozoyik yaşlı masif arazidir."],
"Biga Masifi":["Biga Yarımadası'nda, Çanakkale çevresindeki masif arazidir."],
"Kazdağı Masifi":["Edremit Körfezi'nin kuzeyindeki masif; kırılarak Kaz Dağları horstunu oluşturmuştur."],
"Uludağ Masifi":["Bursa'nın güneyindeki masif arazidir; Uludağ zirvesinde küçük buzul gölleri bulunur."],
"Menderes Masifi":["Ege'nin en geniş masifidir; Gediz, Küçük ve Büyük Menderes grabenleri bu masifin kırılmasıyla oluşmuştur.","Bozdağlar ve Aydın Dağları bu masifin horst kesimleridir."],
"Saruhan-Menteşe Masifi":["Muğla çevresinde, Menderes Masifi'nin güneyindeki masif arazidir."],
"Zonguldak Masifi":["Batı Karadeniz'de, Zonguldak–Amasra–Bartın taşkömürü yataklarının bulunduğu yaşlı arazidir.","Taşkömürü Karbonifer'deki bataklık ormanlarının taşlaşmasıyla oluşmuştur (kitap s.21)."],
"Daday-Devrekani ve Ilgaz Masifi":["Kastamonu çevresindeki masif arazidir; kitapta Daday-Devrekani ve Ilgaz adıyla birlikte gösterilir."],
"Kırşehir Masifi":["İç Anadolu'nun ortasındaki yaşlı masiftir; kitaptaki deprem haritasında Kırşehir'in iç kesimi en az tehlikeli alanlar arasındadır."],
"Akdağmadeni Masifi":["Yozgat'ın doğusundaki masif arazidir."],
"Amasya-Tokat Masifi":["Orta Karadeniz'in iç kesiminde, Amasya ile Tokat arasındaki masif arazidir."],
"Pulur Masifi":["Kuzeydoğu Anadolu'da, Bayburt-Erzurum yöresindeki küçük masif arazidir."],
"Sultandağları Masifi":["Afyonkarahisar-Isparta arasında, Sultan Dağları'nın bulunduğu alandaki masif arazidir."],
"Niğde Masifi":["Niğde'nin doğusundaki masif arazidir."],
"Akdağ Masifi":["Kitapta Niğde Masifi'nin güneybatısında, Toroslar'ın kuzeyinde gösterilen masif arazidir."],
"Alanya-Anamur Masifi":["Akdeniz kıyısında Alanya ile Anamur arasındaki masif arazidir; kıyı burada dik ve girintisizdir."],
"Malatya-Pötürge Masifi":["Malatya'nın güneydoğusundaki masif arazidir."],
"Bitlis Masifi":["Van Gölü'nün güneybatısında, Bitlis çevresindeki geniş masif arazidir."],
"Mardin-Derik Masifi":["Güneydoğu Anadolu'da, Mardin ile Derik arasındaki masif arazidir."],
"Kızılırmak":["Türkiye sınırları içinde doğup denize dökülen en uzun akarsudur; Sivas'tan doğar, yay çizerek Bafra'da Karadeniz'e dökülür.","Alüvyonlarıyla Bafra Ovası (delta) oluşmuştur; üzerinde Hirfanlı ve Altınkaya barajları vardır. Karma rejimlidir."],
"Yeşilırmak":["Karadeniz havzasındadır; Kelkit Çayı ile birleşip Çarşamba Ovası'nı (delta) oluşturarak Karadeniz'e dökülür.","Karma rejimlidir; üzerinde Almus Barajı vardır."],
"Sakarya":["İç Anadolu'dan doğup Karadeniz'e dökülür; alüvyonlarıyla Karasu deltasını oluşturur.","Porsuk en önemli kolu; üzerinde Sarıyar ve Gökçekaya barajları vardır."],
"Filyos (Yenice)":["Batı Karadeniz'de, Zonguldak'ın doğusunda Karadeniz'e dökülen akarsudur; yukarı kesimi Yenice Çayı olarak bilinir."],
"Çoruh":["Doğu Karadeniz'de Mescit Dağları'ndan doğar, Artvin'den Gürcistan'a geçip Batum'da Karadeniz'e dökülür (Karadeniz havzası).","Deriner ve Yusufeli barajları üzerindedir; derin ve dar vadisiyle rafting için elverişlidir."],
"Fırat":["Erzurum Dumlu Dağları'ndan doğan Karasu ile Ağrı'dan gelen Murat'ın Elazığ yakınında birleşmesiyle Fırat adını alır.","Suriye ve Irak'a geçer, Irak'ta Dicle ile birleşip Basra Körfezi'ne dökülür. Üzerinde Keban, Karakaya, Atatürk ve Birecik barajları vardır."],
"Dicle":["Diyarbakır'ın kuzeyindeki Hazar Gölü yakınlarından doğar; Irak'a geçip Fırat ile birleşerek Basra Körfezi'ne dökülür.","Kısa bir kesimde Türkiye–Suriye sınırını oluşturur; üzerinde Dicle, Kralkızı ve Ilısu barajları vardır."],
"Aras":["Erzurum'dan doğar, Türkiye–Ermenistan–Nahçıvan sınırını oluşturur ve Kura ile birleşip Hazar Denizi'ne dökülür (kapalı havza).","Kar ve buz sularıyla beslenir; ilkbahar ve yaz başında kabarır."],
"Kura":["Ardahan'dan doğar, Gürcistan ve Azerbaycan'dan geçip Aras ile birleşerek Hazar Denizi'ne dökülür.","Kar-buz sularıyla beslenen akarsulara örnektir; Çıldır Gölü'nün fazla suları Arpaçay ile Kura'ya karışır."],
"Meriç":["Bulgaristan'dan gelir, Türkiye–Yunanistan sınırını oluşturur ve Enez'de Ege Denizi'ne dökülür.","Ergene ve Tunca kollarıdır; ağzında Meriç deltası vardır."],
"Ergene":["Trakya'nın ana akarsuyudur; Meriç'in kolu olarak Ege havzasına bağlanır.","Ergene tektonik ovası boyunca akar; sanayi kaynaklı kirlilikle gündeme gelir."],
"Susurluk (Simav)":["Marmara havzasının başlıca akarsuyudur; Simav Çayı olarak doğup Karacabey yakınında Marmara Denizi'ne ulaşır (açık havza)."],
"Bakırçay":["Balıkesir sınırlarından doğar, Çandarlı Körfezi'nden Ege Denizi'ne dökülür; alüvyonlarıyla Dikili Deltası'nı oluşturur."],
"Gediz":["Kütahya'daki Murat Dağları'ndan doğar, Foça yakınlarında Ege Denizi'ne dökülür; alüvyonlarıyla Menemen Deltası'nı oluşturur.","Üzerinde Demirköprü Barajı vardır."],
"Küçük Menderes":["Bozdağlar'dan doğar, Selçuk yakınında Ege Denizi'ne dökülür; alüvyonlarıyla Efes (Selçuk) Deltası'nı oluşturur."],
"Büyük Menderes":["Afyon Dinar'dan doğar, Aydın Ovası'nı geçerek Ege Denizi'ne ulaşır; alüvyonlarıyla Balat Deltası'nı oluşturur.","Menderesleriyle (büklüm) ünlüdür; üzerinde Adıgüzel Barajı vardır."],
"Dalaman Çayı":["Akdeniz havzasındadır; Muğla-Dalaman'da denize dökülür.","Karstik kaynaklarla beslendiği için debisi yıl boyunca düzenlidir (kitap s.94); getirdiği alüvyonlar Köyceğiz Gölü'nü denizden ayırmıştır."],
"Eşen Çayı":["Teke yöresinden inip Fethiye-Kaş arasında Akdeniz'e dökülen akarsudur (Akdeniz havzası)."],
"Aksu Çayı":["Göller Yöresi'nden gelen suları Akdeniz'e taşır; Eğirdir'in fazla suları Kovada Gölü üzerinden Aksu ile Akdeniz'e ulaşır (kitap s.98)."],
"Köprüçay":["Batı Toroslar'dan doğup Antalya'nın doğusunda Akdeniz'e dökülür; Köprülü Kanyon rafting parkuruyla bilinir."],
"Manavgat Çayı":["Toroslar'dan doğup Manavgat'ta Akdeniz'e dökülür.","Karstik kaynaklarla beslendiği için yıl boyu düzenli akar (kitap s.94); üzerinde Oymapınar ve Manavgat barajları ile Manavgat Şelalesi vardır."],
"Göksu (Silifke)":["Toros Dağları'ndan doğar, Silifke'den geçer ve Akdeniz'e dökülür; alüvyonlarıyla Silifke Deltası'nı oluşturur.","Üzerinde Ermenek Barajı vardır; Göksu Deltası Ramsar alanıdır."],
"Seyhan":["Kayseri'den doğar, Adana yakınında Akdeniz'e dökülür; alüvyonlarıyla Çukurova'yı oluşturur.","Karma rejimlidir; üzerinde Çatalan Barajı vardır."],
"Ceyhan":["Kahramanmaraş yöresinden doğar, Akdeniz'e dökülür; alüvyonlarıyla Çukurova Deltası'nı oluşturur.","Üzerinde Aslantaş ve Berke barajları vardır."],
"Asi":["Lübnan'dan doğar, Suriye'den geçip Hatay'dan Türkiye'ye girer ve Samandağ'da Akdeniz'e dökülür.","Türkiye–Suriye arasında sınır oluşturan akarsulardandır."],
"Porsuk Çayı":["Sakarya Nehri'nin kolu; Kütahya ve Eskişehir'den geçer."],
"Devrez Çayı":["Kızılırmak'ın kolu; Ilgaz Dağları'nın güneyinden akar."],
"Kelkit Çayı":["Yeşilırmak'ın en önemli kolu; Kuzey Anadolu Fay Hattı boyunca akar."],
"Karasu (Fırat kolu)":["Erzurum Dumlu Dağları'ndan doğar; Murat ile birleşince Fırat adını alır."],
"Murat":["Ağrı yöresinden doğar, Elazığ yakınında Karasu ile birleşerek Fırat'ı oluşturur; Muş Ovası'ndan geçer."],
"Zap Suyu":["Hakkâri Dağları arasından akarak Dicle'ye karışan kol; Basra Körfezi havzasındadır."],
"Harşit Çayı":["Gümüşhane'den doğup Tirebolu'da Karadeniz'e dökülen akarsudur."],
"Delice Irmağı":["Kızılırmak'ın kolu; Yozgat-Kırıkkale arasında akar."],
"Gönen Çayı":["Marmara havzasında, Balıkesir-Gönen'den geçip Marmara Denizi'ne dökülür."],
"Bartın Çayı":["Batı Karadeniz'de Bartın'dan geçer; denize yakın kesiminde küçük teknelerle ulaşım yapılabildiği için KPSS'de ulaşıma elverişli akarsu örneği olarak geçer."],
"Tunca":["Bulgaristan'dan gelir, Edirne'de Meriç'e karışır; kısa bir kesimde Türkiye–Bulgaristan sınırını oluşturur."],
"Mutludere":["Trakya'nın kuzeyinde Türkiye–Bulgaristan sınırını oluşturarak Karadeniz'e dökülür."],
"Arpaçay":["Kars'ta Türkiye–Ermenistan sınırını oluşturur ve Aras'a karışır; Çıldır Gölü'nün fazla suları bu akarsuyla Kura'ya ulaşır."],
"Hezil Çayı":["Şırnak'ta Türkiye–Irak sınırını oluşturur ve Dicle'ye karışır."],
"Van Gölü":["Kitapta karma oluşumlu göl: çanağı tektonik çöküntüdür, Nemrut lavlarının batıyı kapatmasıyla akışı engellenmiştir.","Türkiye'nin en büyük, dünyanın en büyük sodalı gölüdür; kapalı havza, suları tuzlu-sodalı (içme ve sulamada kullanılmaz).","Yalnızca inci kefali yaşar; ilkbaharda üremek için tatlı su derelerine göç eder."],
"Tuz Gölü":["Konya–Aksaray–Ankara üçgeninde tektonik kökenli, kapalı havza gölüdür.","Suları çok tuzludur; yazın büyük ölçüde kurur. Türkiye'nin tuz üretimindeki en önemli kaynağıdır."],
"Seyfe Gölü":["Kırşehir'de tektonik kökenli, kapalı havza gölüdür; suları tuzlu-sodalıdır.","Göçmen kuşlar için önemlidir ve Ramsar alanıdır."],
"Aktaş Gölü":["Ardahan'da tektonik kökenli sınır gölüdür; yaklaşık üçte ikisi Türkiye'de, kalanı Gürcistan'dadır. Kapalı havza özelliği taşır."],
"Hazar Gölü":["Elazığ'da tektonik göldür; çevresinde plajlar, kamp alanları ve Hazarbaba Kayak Merkezi vardır.","Dicle bu gölün yakınlarından doğar."],
"Manyas (Kuş) Gölü":["Balıkesir'de tektonik kökenli, tatlı sulu göldür; Kuş Cenneti Milli Parkı ile ünlüdür, Ramsar alanıdır."],
"Uluabat Gölü":["Bursa'da tektonik kökenli, tatlı sulu göldür; kuş çeşitliliği zengindir ve Ramsar alanıdır."],
"İznik Gölü":["Marmara Bölgesi'nin en büyük gölüdür; tektonik kökenli ve tatlı suludur.","Çevresinde tarım, balıkçılık ve turizm gelişmiştir."],
"Burdur Gölü":["Tektonik kökenli, suları tuzlu-sodalı göldür; uluslararası öneme sahip Ramsar alanıdır."],
"Sapanca Gölü":["Sakarya'da tektonik kökenli tatlı su gölüdür; kitap haritasında tektonik göller arasında gösterilir."],
"Eber Gölü":["Afyonkarahisar'da tektonik kökenli göldür; Akşehir Gölü'nün kuzeyindedir."],
"Akşehir Gölü":["Konya-Afyonkarahisar arasında tektonik kökenli göldür; son yıllarda büyük ölçüde kurumuştur."],
"Acıgöl (Denizli)":["Denizli-Afyonkarahisar sınırında tektonik kökenli, tuzlu göldür; sodyum sülfat üretimi yapılır."],
"Nemrut Krater Gölü":["Bitlis–Tatvan yakınlarında Nemrut Volkanı'nın kalderasındadır; büyük patlama sonrası çöken kaldera çukurunda suların birikmesiyle oluşmuştur."],
"Meke Gölü":["Konya–Karapınar'da bir maar (patlama krateri) içine su birikmesiyle oluşmuş volkanik göldür; 'Dünyanın nazar boncuğu' olarak anılır."],
"Acıgöl (Karapınar)":["Konya–Karapınar'da Meke Gölü yakınındaki volkanik (maar) göldür."],
"Salda Gölü":["Burdur'da karstik kökenli, kapalı havza gölüdür; beyaz kumsallarıyla 'Türkiye'nin Maldivleri' olarak bilinir."],
"Avlan Gölü":["Antalya–Elmalı'da karstik göldür; 1970'lerde tarım için kısmen kurutulmuş, sonra yeniden su tutmaya başlamıştır."],
"Kızören Obruğu":["Konya'da bir obruk içinde oluşmuş karstik göldür; suları tuzlu-sodalıdır, seviyesi mevsimlere göre değişir."],
"Hafik Gölü":["Sivas'ta jips (alçı taşı) tabakalarının çözünmesiyle oluşmuş tipik karstik göldür."],
"Tödürge Gölü":["Sivas'ta Hafik Gölü yakınında jipsli arazide oluşmuş karstik göldür."],
"Eğirdir Gölü":["Kitapta tektonik-karstik (karma) göl: önce tektonik çukurluk, sonra karstik çözünme ile genişlemiştir.","Fazla suları güney ucundaki eşik ve yeraltı sızmalarıyla Kovada Gölü'ne, oradan Aksu Çayı ile Akdeniz'e ulaşır (gidegenli göl)."],
"Kovada Gölü":["Eğirdir Gölü'nün güneyinde tektonik-karstik (karma) göldür; Eğirdir'in fazla sularını alır ve Aksu Çayı'na aktarır."],
"Beyşehir Gölü":["Tektonik-karstik (karma) göldür; gidegenlidir. Fazla suları Beyşehir Kanalı ile Suğla Gölü'ne aktarılır.","Bu sular Konya Kapalı Havzası'nda kaldığından denize ulaşmaz; kitapta 'yapay gidegenli kapalı havza gölü' olarak tanımlanır."],
"Suğla Gölü":["Beyşehir Gölü'nün fazla sularını alan karma göldür; burada biriken sular galeriler ve pompalarla Çumra Ovası'na sulama suyu olarak verilir."],
"Abant Gölü":["Bolu'da heyelan set gölüdür; heyelanla kayan malzemenin vadiyi kapatmasıyla oluşmuştur."],
"Yedigöller":["Bolu'da heyelan set gölleri grubudur; milli park alanıdır."],
"Borabay Gölü":["Amasya–Taşova'da heyelan set gölüdür."],
"Zinav Gölü":["Tokat–Reşadiye'de heyelan set gölüdür."],
"Sera Gölü":["Trabzon'da heyelan set gölüdür."],
"Tortum Gölü":["Erzurum'da heyelan set gölüdür; gölden çıkan sular setin üzerinden 48 m'den dökülerek Türkiye'nin en yüksek şelalesi Tortum Şelalesi'ni oluşturur.","Tortum HES bölgenin enerji ihtiyacına katkı sağlar."],
"Uzungöl":["Trabzon'da alüvyal set gölüdür; akarsuyun taşıdığı alüvyonların vadiyi kapatmasıyla oluşmuştur."],
"Mogan Gölü":["Ankara–Gölbaşı'nda alüvyal set gölüdür."],
"Eymir Gölü":["Ankara–Gölbaşı'nda Mogan'ın kuzeyindeki alüvyal set gölüdür."],
"Marmara Gölü":["Manisa'da Gediz alüvyonlarıyla oluşmuş alüvyal set gölüdür."],
"Bafa Gölü":["Büyük Menderes'in taşıdığı alüvyonların Latmos Körfezi'nin önünü kapatmasıyla oluşmuş alüvyal set gölüdür; eskiden Ege Denizi'nin bir parçasıydı."],
"Köyceğiz Gölü":["Dalaman Çayı'nın getirdiği alüvyonlarla kapanıp Akdeniz'den ayrılan alüvyal set gölüdür."],
"Çıldır Gölü":["Ardahan–Kars sınırında lav set gölüdür; Doğu Anadolu'nun yüzölçümü bakımından en büyük tatlı su gölüdür.","Kışın tamamen donar; üzerinde yürünebilir ve atlı kızaklarla ulaşım sağlanır. Fazla suları Arpaçay ile Kura'ya karıştığı için açık havza gölüdür."],
"Balık Gölü":["Ağrı'da lavların vadiyi kapatmasıyla oluşmuş lav set gölüdür."],
"Haçlı Gölü":["Muş–Bulanık'ta lav set gölüdür."],
"Nazik Gölü":["Bitlis–Ahlat'ta Van Gölü'nün kuzeybatısındaki lav set gölüdür."],
"Erçek Gölü":["Van'ın doğusunda, kitapta lav set gölü olarak gösterilen sodalı göldür."],
"Terkos (Durusu) Gölü":["Türkiye'deki kıyı set gölleri (lagün) arasında en büyük ve en önemlisidir; içme suyu kaynağı olarak kullanılması onu diğer lagünlerden ayırır."],
"Büyükçekmece Gölü":["İstanbul'da kıyı set gölüdür (lagün); yoğun yerleşim, sanayi ve ulaşım baskısı altındadır."],
"Küçükçekmece Gölü":["İstanbul'da kıyı set gölüdür (lagün); çevresindeki ekosistem tehdit altındadır."],
"Ölüdeniz":["Fethiye'de Türkiye'nin en tanınmış kıyı set gölüdür; denizle dar bir kanalla bağlantılıdır, bu nedenle tuzludur."],
"Akyatan Lagünü":["Adana'da Akdeniz kıyısında kıyı set gölüdür; göçmen kuşlar için önemlidir."],
"Yumurtalık Lagünü":["Adana–Yumurtalık yakınlarında kıyı set gölüdür; Ramsar Sözleşmesi kapsamında koruma altındadır."],
"Akgöl (Göksu Deltası)":["Göksu Deltası'ndaki lagündür; delta 1994'te Ramsar alanı ilan edildiği için Ramsar statüsündedir."],
"Otlukbeli Gölü":["Erzincan'da Türkiye'nin ve dünyanın bilinen tek traverten set gölüdür; suları tatlıdır.","Kalsiyum karbonatça zengin yeraltı sularının çökelttiği traverten birikintilerinin vadiyi kapatmasıyla oluşmuştur."],
"Atatürk Barajı":["Fırat üzerinde, Türkiye'nin en büyük barajıdır; GAP'ın temelidir ve Şanlıurfa Tünelleri ile Harran Ovası'nı sular."],
"Karakaya Barajı":["Fırat üzerinde, en büyük barajlar sıralamasında ikincidir."],
"Keban Barajı":["Fırat üzerinde Elazığ'dadır; en büyük barajlar sıralamasında üçüncüdür."],
"Ilısu Barajı":["Dicle üzerinde Mardin–Şırnak arasındadır; en büyük barajlar sıralamasında dördüncüdür."],
"Altınkaya Barajı":["Kızılırmak üzerinde Samsun'dadır; en büyük barajlar sıralamasında beşincidir."],
"Birecik Barajı":["Fırat üzerinde Şanlıurfa'dadır; en büyük barajlar sıralamasında altıncıdır."],
"Deriner Barajı":["Çoruh üzerinde Artvin'dedir; en büyük barajlar sıralamasında yedincidir."],
"Oymapınar Barajı":["Manavgat Çayı üzerindedir; en büyük barajlar sıralamasında sekizincidir."],
"Berke Barajı":["Ceyhan üzerinde Osmaniye'dedir; en büyük barajlar sıralamasında dokuzuncudur."],
"Ermenek Barajı":["Göksu üzerinde Karaman'dadır; en büyük barajlar sıralamasında onuncudur."],
"Asidik Kahverengi Orman Toprakları":["Nemli iklim bölgelerinde geniş yapraklı ve iğne yapraklı orman örtüsü altında oluşur; fazla yağış kireç ve mineralleri yıkar, toprak asit yapı kazanır.","Organik madde ve humusça zengin, koyu renkli ve verimlidir; çay, fındık ve kivi gibi neme duyarlı ürünler için elverişlidir. Özellikle Doğu ve Batı Karadeniz'de denize bakan yamaçlarda görülür."],
"Kireçli Orman Toprakları":["Yağışın azaldığı bölgelerdeki orman örtüsü altında oluşur; yıkanma az olduğundan kireç ve mineraller toprakta kalır.","pH değeri yüksek, bazik; rengi açık, yapısı gevşektir. Yağışın daha az olduğu iç kesimlerdeki ormanlık alanlarda görülür (haritada taralı alan)."],
"Terra Rossa Toprakları":["Türkiye'de en yaygın zonal topraklardandır; Akdeniz ikliminde kalkerli ana kaya üzerinde oluşur.","Kimyasal çözünmeyle kireç uzaklaşırken demir oksit kırmızı renk verir; zeytin, turunçgil, bağ ve tahıl için elverişlidir. Güney Marmara, Ege kıyıları ve Akdeniz'de, özellikle denize bakan yamaçlarda yaygındır."],
"Bozkır Toprakları":["Yarı kurak karasal iklimde bozkır bitki örtüsü altında oluşur; humus azdır, verim düşüktür. Buğday, arpa, şeker pancarı ve baklagiller için uygundur.","Kahverengi bozkır toprakları 250–400 mm, kestane rengi bozkır toprakları 400–600 mm yağış alan alanlarda görülür. İç, Güneydoğu ve Doğu Anadolu'da yaygındır."],
"Taşlı ve Kumlu Topraklar":["İnce taneli madde az, iri taneli parçalar fazladır; su ve besin tutma kapasiteleri düşüktür. Fiziksel ayrışmanın etkili olduğu alanlarda oluşur.","Regosol: gevşek, humusça fakir genç topraklar (İç Anadolu'daki patates alanları). Litosol: eğimli yamaçlarda ince, taşlı, tarıma elverişsiz topraklar."],
"Çernezyom Toprakları":["Dünyanın en verimli topraklarındandır; karasal iklimlerde çayır örtüsü altında oluşan koyu siyah, humusça zengin 'kara topraklar'dır.","Türkiye'de Erzurum–Kars Platosu'nda görülür; iklim sert olduğu için tarımda yaygın kullanılamaz, büyükbaş hayvancılıkta kullanılır."],
"Vertisol (Dönen) Topraklar":["Kalsimorfik topraktır: eski göl tabanlarında killi ve kireçli ana materyal üzerinde oluşur; kuruyunca çatlayıp yağışla genişleyerek yüzeye döner.","Halk arasında 'kepir toprak, taş doğuran toprak' olarak bilinir; haritada Trakya'da gösterilmiştir."],
"Rendzina Toprakları":["Kalsimorfik topraktır: yumuşak kireçtaşı üzerinde oluşan koyu renkli, humusça zengin topraklardır.","Karstik alanlarda görülür; verimlidir ancak derinlikleri genellikle azdır."],
"Alüvyal Topraklar":["Akarsuların taşıyıp vadi tabanlarında, ovalarda ve deltalarda biriktirdiği ince malzemelerden oluşan taşınmış (azonal) genç topraklardır; horizonları belirgin değildir.","Humus ve mineralce zengindir; tarım için en elverişli topraklardır. En geniş alanlar: Çukurova, Bafra, Çarşamba, Gediz ve Sakarya ovaları."],
"Karadeniz Havzası":["Türkiye'nin en geniş açık havzasıdır; Kızılırmak, Yeşilırmak, Filyos, Çoruh ve Sakarya Karadeniz'e dökülür."],
"Marmara Havzası":["Açık havza; Susurluk Nehri Marmara Denizi'ne ulaşır."],
"Ege Havzası":["Açık havza; Bakırçay, Gediz, Küçük Menderes, Büyük Menderes ve Meriç Ege Denizi'ne dökülür."],
"Akdeniz Havzası":["Açık havza; Dalaman, Eşen, Manavgat, Köprüçay, Aksu, Göksu, Seyhan, Ceyhan ve Asi akarsularından oluşur."],
"Basra Körfezi Havzası":["Açık havza; Fırat, Dicle ve Zap Türkiye'den doğar, ülke dışında birleşerek Basra Körfezi'ne ulaşır."],
"Hazar Havzası":["Doğu Anadolu'da; Aras ve Kura Türkiye'den doğup dışarıya çıkarak birleşir ve Hazar Denizi'ne ulaşır. Kitapta kapalı havza olarak sınıflanır."],
"Van Gölü Havzası":["Doğu Anadolu'da kapalı havza; akarsular Van Gölü'ne dökülür."],
"Tuz Gölü Havzası":["İç Anadolu'da kapalı havza; akarsular sularını Tuz Gölü'ne boşaltır."],
"Göller Yöresi Havzası":["Batı Akdeniz'de (Isparta, Burdur çevresi) kapalı havza; akarsuların suları dışarıya ulaşamaz, göllerde son bulur.","Havzanın kapalı olmasında karstik yapı ve dış drenaj bağlantısının olmaması etkilidir."],
"1. derece deprem bölgesi":["Çok şiddetli ve yıkıcı depremler beklenir; KAF (Marmara–Erzincan), DAF (Bingöl–Hatay) ve Ege graben fayları boyunca uzanır."],
"2. derece deprem bölgesi":["Şiddetli depremlerin beklendiği, 1. derece kuşakları çevreleyen alanlardır."],
"3. derece deprem bölgesi":["Orta şiddetli depremlerin beklendiği alanlardır; İç Anadolu'nun büyük bölümü ve Güneydoğu'nun bir kısmı."],
"4. derece deprem bölgesi":["Az şiddetli depremlerin beklendiği alanlardır; Trakya'nın kuzeyi, Doğu Karadeniz kıyısı ve İç Anadolu'nun bazı kesimleri."],
"5. derece deprem bölgesi":["Hafif şiddetli depremlerin beklendiği en düşük tehlikeli alandır; kitap haritasında Konya–Karaman çevresi ve Kırşehir'in iç kesimi."]

};
